import Foundation

extension L10n {
    static let zh: [String: String] = [
        "app.name": "EnvMatrix",
        "app.welcome.title": "欢迎使用 EnvMatrix",
        "app.welcome.subtitle": "请从左侧边栏选择一项以开始使用。",
        "app.underConstruction": "此模块正在建设中。",

        "nav.overview": "概览",
        "nav.devEnvironments": "开发环境",
        "nav.packages": "包管理",
        "nav.packagesSystem": "系统包管理",
        "nav.packagesLangs": "语言全局环境",
        "nav.projectEnvGroup": "项目本地环境",
        "nav.aiEnvironments": "AI 环境",
        "nav.system": "系统",
        "nav.dashboard": "仪表盘",
        "nav.homebrew": "Homebrew",
        "nav.mavenRepo": "Java 全局环境",
        "nav.skills": "技能",
        "nav.aiCLI": "AI 命令行",
        "nav.mcpServers": "MCP 服务器",
        "nav.settings": "设置",
        "nav.shellEnv": "Shell 本地环境",
        "shellEnv.title": "Shell 本地环境",
        "shellEnv.currentShell": "当前 shell",
        "shellEnv.mode": "视图",
        "shellEnv.mode.structured": "结构化",
        "shellEnv.mode.raw": "原文",
        "shellEnv.export": "export",
        "shellEnv.key": "变量名",
        "shellEnv.value": "值",
        "shellEnv.quoting": "引号",
        "shellEnv.quoting.double": "双引号",
        "shellEnv.quoting.single": "单引号",
        "shellEnv.quoting.none": "无",
        "shellEnv.addVariable": "新增变量",
        "shellEnv.addPathGroup": "新增 PATH 组",
        "shellEnv.removePathGroup": "删除本组",
        "shellEnv.addSegment": "追加",
        "shellEnv.removeSegment": "删除",
        "shellEnv.segment.placeholder": "输入路径片段…",
        "shellEnv.unparsedLines": "未解析行数",
        "shellEnv.sectionVariables": "变量",
        "shellEnv.sectionPath": "PATH 追加",
        "shellEnv.save": "保存",
        "shellEnv.refresh": "刷新",
        "shellEnv.emptySelect": "请选择一个文件",
        "shellEnv.emptySelect.hint": "从左侧选择要编辑的 shell 配置文件。",

        "nav.hosts": "Hosts 管理",
        "hosts.title": "Hosts 管理",
        "hosts.mode": "视图",
        "hosts.mode.structured": "结构化",
        "hosts.mode.raw": "原文",
        "hosts.sectionEntries": "条目",
        "hosts.addEntry": "新增条目",
        "hosts.removeEntry": "删除",
        "hosts.entry.enabled": "启用",
        "hosts.entry.ip": "IP",
        "hosts.entry.hostnames": "主机名（空格分隔）",
        "hosts.entry.comment": "注释",
        "hosts.unparsedLines": "未解析行数",
        "hosts.systemPath": "系统文件",
        "hosts.matchesSystem": "与 /etc/hosts 一致",
        "hosts.newProfile": "新建方案",
        "hosts.duplicate": "另存为",
        "hosts.rename": "重命名",
        "hosts.delete": "删除",
        "hosts.setDefault": "设为默认",
        "hosts.default": "默认",
        "hosts.saveProfile": "保存方案",
        "hosts.applyToSystem": "应用到 /etc/hosts",
        "hosts.applyConfirm.title": "应用到 /etc/hosts？",
        "hosts.applyConfirm.message": "将覆盖 /etc/hosts，覆盖前会在应用支持目录生成带时间戳的备份，需要管理员授权。",
        "hosts.applyConfirm.ok": "应用",
        "hosts.cancel": "取消",
        "hosts.ok": "确定",
        "hosts.refresh": "刷新",
        "hosts.profileName": "方案名称",
        "hosts.emptySelect": "请选择一个方案",
        "hosts.emptySelect.hint": "从左侧选择一个 hosts 方案，或新建一个。",

        "dashboard.title": "仪表盘",
        "dashboard.subtitle": "本地开发和 AI 环境的总览",
        "dashboard.refresh": "刷新",
        "dashboard.runtimeSuffix": "运行时",
        "dashboard.current": "当前",
        "dashboard.notSet": "未设置",
        "dashboard.system": "系统",
        "dashboard.installed": "已安装",
        "dashboard.configured": "已配置",
        "dashboard.storage": "存储",
        "dashboard.skills": "技能",
        "dashboard.mcpServers": "MCP 服务器",
        "dashboard.activeRuntimes": "已启用运行时",
        "dashboard.managed": "已托管",
        "dashboard.section.runtimes": "运行时",
        "dashboard.section.overview": "总览",
        "dashboard.section.packages": "包管理器",
        "dashboard.packages.refresh": "重新扫描包缓存",
        "dashboard.package.cacheSize": "缓存占用",
        "dashboard.package.needsCleanup": "建议清理",
        "dashboard.attention": "需要关注",
        "dashboard.storage.subtitle": "托管版本占用",
        "dashboard.card.openHint": "打开详情",

        "runtime.installed": "已安装",
        "runtime.available": "可用版本",
        "runtime.active": "当前",
        "runtime.none": "无",
        "runtime.systemDefault": "系统默认",
        "runtime.refresh": "刷新",
        "runtime.loading": "正在加载版本...",
        "runtime.noAvailable": "没有可用版本。",
        "runtime.noInstalled": "尚未安装任何版本。切换到\"可用版本\"进行安装。",
        "runtime.install": "安装",
        "runtime.installedLabel": "已安装",
        "runtime.setActive": "设为活动",
        "runtime.uninstall": "卸载",
        "runtime.uninstallTitle": "卸载 %@?",
        "runtime.cancel": "取消",
        "runtime.revealInFinder": "在访达中显示",
        "runtime.uninstallSystemMessage": "EnvMatrix 将删除以下文件夹:\n%@\n\n如果它是通过 brew / sdkman / nvm / pkg 安装的，使用其自带的卸载工具会更安全。系统所属的路径可能需要 sudo 权限，将被拒绝。",
        "runtime.uninstallMessage": "此操作将从系统中移除 %@ %@。",
        "runtime.uninstallSystemTooltip": "卸载此系统运行时（删除前会二次确认）",
        "runtime.uninstallTooltip": "卸载此版本",
        "runtime.systemBadge": "系统",
        "runtime.usage": "用量",
        "runtime.usage.total": "总占用",
        "runtime.usage.loading": "正在计算磁盘占用…",
        "runtime.usage.empty": "尚未安装任何版本，无法统计占用。",
        "runtime.usage.unknown": "未知",
        "runtime.usage.managed": "托管",
        "runtime.usage.system": "系统",
        "runtime.usage.recompute": "重新计算",
        "runtime.group.managed": "托管版本",
        "runtime.group.system": "系统版本",
        "runtime.group.count": "%d",

        "skills.title": "技能",
        "skills.refresh": "刷新",
        "skills.empty.title": "未找到技能",
        "skills.empty.subtitle": "配置的技能目录为空。",
        "skills.revealInFinder": "在访达中显示",
        "skills.delete": "删除",
        "skills.source.unknown": "未分类",

        "cli.title": "AI 命令行",
        "cli.save": "保存",
        "cli.selectPrompt": "请选择一个 CLI 配置",
        "cli.selectHint": "在左侧选择一项配置以编辑其内容。",
        "cli.model": "模型",
        "cli.apiBaseURL": "API 基础地址",
        "cli.apiKey": "API 密钥",

        "mcp.title": "MCP 服务器",
        "mcp.add": "添加",
        "mcp.refresh": "刷新",
        "mcp.empty.title": "暂无 MCP 服务器",
        "mcp.empty.subtitle": "点击\"添加\"以配置新的服务器。",
        "mcp.edit": "编辑",
        "mcp.delete": "删除",
        "mcp.argCount.one": "%d 个参数",
        "mcp.argCount.many": "%d 个参数",
        "mcp.transport.npx": "npx",
        "mcp.transport.uvx": "uvx",
        "mcp.transport.node": "Node.js",
        "mcp.transport.python": "Python",
        "mcp.transport.other": "其他",
        "mcp.editor.editTitle": "编辑 MCP 服务器",
        "mcp.editor.addTitle": "添加 MCP 服务器",
        "mcp.editor.basics": "基本信息",
        "mcp.editor.name": "名称",
        "mcp.editor.command": "命令",
        "mcp.editor.arguments": "参数",
        "mcp.editor.argsPlaceholder": "以逗号分隔",
        "mcp.editor.argsHelp": "多个值用英文逗号分隔，例如: --port,8080",
        "mcp.editor.envVars": "环境变量",
        "mcp.editor.envKey": "键",
        "mcp.editor.envValue": "值",
        "mcp.editor.addVariable": "添加变量",
        "mcp.editor.cancel": "取消",
        "mcp.editor.save": "保存",

        "settings.general": "通用",
        "settings.logs": "日志",
        "settings.about": "关于",
        "settings.appearance": "外观",
        "settings.colorScheme": "配色方案",
        "settings.system": "跟随系统",
        "settings.light": "浅色",
        "settings.dark": "深色",
        "settings.language": "语言",
        "settings.languageLabel": "界面语言",
        "settings.mirrors": "镜像源",
        "settings.nodeMirror": "Node.js 镜像",
        "settings.pythonMirror": "Python 镜像",
        "settings.goMirror": "Go 镜像",
        "settings.javaMirror": "Java 镜像",
        "settings.resetDefaults": "恢复默认",
        "settings.entries": "共 %d 条",
        "settings.clear": "清除",
        "settings.noLogs": "暂无日志。",
        "settings.version": "版本 %@",
        "settings.aboutDescription": "一款统一的 macOS 控制面板，用于管理开发者运行时和 AI 开发环境。",
        "settings.viewGitHub": "在 GitHub 上查看",

        "brew.title": "Homebrew",
        "brew.notInstalled.title": "未找到 Homebrew",
        "brew.notInstalled.subtitle": "EnvMatrix 在 /opt/homebrew/bin/brew 或 /usr/local/bin/brew 未找到 brew 可执行文件。请先安装 Homebrew。",
        "brew.formulae": "Formula",
        "brew.casks": "Cask",
        "brew.refresh": "刷新",
        "brew.loading": "正在加载 Homebrew 清单…",
        "brew.emptyList": "当前筛选条件下没有匹配的包。",
        "brew.searchPlaceholder": "搜索名称或描述",
        "brew.outdatedCount": "%d 个可升级",
        "brew.upgradeAll": "全部升级",
        "brew.cleanup": "清理缓存",
        "brew.update": "更新元数据",
        "brew.filter.outdatedOnly": "仅显示可升级",
        "brew.filter.requestedOnly": "仅显示手动安装",
        "brew.action.upgrade": "升级",
        "brew.action.uninstall": "卸载",
        "brew.action.pin": "锁定版本",
        "brew.action.unpin": "解锁版本",
        "brew.action.openHomepage": "打开主页",
        "brew.detail.selectHint": "在左侧选择一个包以查看详情。",
        "brew.detail.kind": "类型",
        "brew.detail.installedVersion": "已安装",
        "brew.detail.latestVersion": "最新版本",
        "brew.detail.homepage": "主页",
        "brew.detail.autoUpdates": "自动更新",
        "brew.detail.installedAt": "安装时间",
        "brew.detail.deprecationReason": "废弃原因",
        "brew.detail.dependencies": "依赖",
        "brew.yes": "是",
        "brew.no": "否",

        "mavenRepo.title": "Java 全局环境",
        "mavenRepo.subtitle": "扫描 Maven 本地仓库 ~/.m2/repository，管理 settings.xml 镜像与依赖",
        "mavenRepo.refresh": "刷新",
        "mavenRepo.addPreset": "添加预设",
        "mavenRepo.settingsFile": "settings.xml：",
        "mavenRepo.localRepository": "本地仓库：",
        "mavenRepo.active": "已启用",
        "mavenRepo.mirrorOfFormat": "mirrorOf：%@",
        "mavenRepo.empty.title": "尚未配置镜像",
        "mavenRepo.empty.subtitle": "点击右上角 + 号添加预设镜像（阿里云 / 腾讯云 / 华为云 / 网易）。",
        "mavenRepo.tab.mirrors": "镜像源",
        "mavenRepo.tab.localArtifacts": "本地依赖",
        "mavenRepo.tab.gradleCache": "Gradle 缓存",
        "mavenRepo.artifact.searchPlaceholder": "搜索 groupId、artifactId 或 version",
        "mavenRepo.artifact.countFormat": "共 %d 个依赖",
        "mavenRepo.artifact.totalSizeFormat": "总计：%@",
        "mavenRepo.artifact.versionCountFormat": "%d 个版本",
        "mavenRepo.artifact.sortByName": "按名称排序",
        "mavenRepo.artifact.sortBySize": "按大小排序",
        "mavenRepo.artifact.sortByModified": "按修改时间排序",
        "mavenRepo.artifact.ascending": "升序",
        "mavenRepo.artifact.loading": "正在扫描本地仓库…",
        "mavenRepo.artifact.notFound.title": "未找到本地仓库",
        "mavenRepo.artifact.notFound.subtitle": "路径 %@ 不存在。\n\n请先运行一次 Maven 构建以生成 ~/.m2/repository。",
        "mavenRepo.artifact.empty.title": "暂无依赖",
        "mavenRepo.artifact.empty.subtitle": "当前搜索条件下没有下载的依赖。",
        "mavenRepo.artifact.deleteAll": "删除所有版本",
        "mavenRepo.artifact.confirmDelete": "删除 %@？",
        "mavenRepo.artifact.confirmDeleteVersion": "删除 %@（%@）？",
        "mavenRepo.artifact.confirmDeleteMessage": "此操作将从磁盘移除 %@，无法撤销。",

        "nav.goRepo": "Go 全局环境",
        "nav.nodeRepo": "Node 全局环境",
        "nav.pythonRepo": "Python 全局环境",
        "goRepo.title": "Go 仓库",
        "goRepo.subtitle": "管理 GOPROXY 镜像并清理本地 GOMODCACHE",
        "goRepo.tab.proxy": "GOPROXY",
        "goRepo.tab.localCache": "本地模块",
        "goRepo.proxy.current": "当前 GOPROXY：",
        "goRepo.proxy.applyPreset": "应用预设",
        "goRepo.proxy.customPlaceholder": "自定义 GOPROXY（英文逗号分隔）",
        "goRepo.proxy.save": "保存",
        "goRepo.proxy.saved": "GOPROXY 已更新",
        "goRepo.cache.searchPlaceholder": "搜索模块或版本",
        "goRepo.cache.countFormat": "共 %d 个模块",
        "goRepo.cache.totalSizeFormat": "总计：%@",
        "goRepo.cache.versionCountFormat": "%d 个版本",
        "goRepo.cache.sortByName": "按名称排序",
        "goRepo.cache.sortBySize": "按大小排序",
        "goRepo.cache.sortByModified": "按修改时间排序",
        "goRepo.cache.ascending": "升序",
        "goRepo.cache.loading": "正在扫描 GOMODCACHE…",
        "goRepo.cache.notFound.title": "未找到 GOMODCACHE",
        "goRepo.cache.notFound.subtitle": "路径 %@ 不存在。\n\n请先执行一次 Go 构建以生成模块缓存。",
        "goRepo.cache.empty.title": "暂无模块",
        "goRepo.cache.empty.subtitle": "当前搜索条件下没有下载的模块。",
        "goRepo.cache.deleteAll": "删除所有版本",
        "goRepo.cache.confirmDelete": "删除 %@？",
        "goRepo.cache.confirmDeleteVersion": "删除 %@（%@）？",
        "goRepo.cache.confirmDeleteMessage": "此操作将从磁盘移除 %@，无法撤销。",
        "goRepo.goMissing.title": "未检测到 Go",
        "goRepo.goMissing.subtitle": "PATH 上未找到 `go` 命令。请先在开发环境中安装 Go。",
        "nodeRepo.title": "Node 仓库",
        "nodeRepo.subtitle": "管理 npm 镜像、全局包与缓存",
        "nodeRepo.tab.registry": "镜像",
        "nodeRepo.tab.global": "全局包",
        "nodeRepo.tab.cache": "缓存",
        "nodeRepo.registry.current": "当前镜像：",
        "nodeRepo.registry.applyPreset": "应用预设",
        "nodeRepo.registry.customPlaceholder": "自定义镜像 URL",
        "nodeRepo.registry.save": "保存",
        "nodeRepo.registry.saved": "镜像已更新",
        "nodeRepo.registry.confirmTitle": "更新 npm 镜像？",
        "nodeRepo.registry.confirmMessage": "~/.npmrc 中的 registry 将改为 %@，并生成备份 ~/.npmrc.envmatrix.bak。",
        "nodeRepo.global.searchPlaceholder": "搜索包名",
        "nodeRepo.global.countFormat": "共 %d 个包",
        "nodeRepo.global.loading": "正在加载全局包…",
        "nodeRepo.global.empty.title": "暂无全局包",
        "nodeRepo.global.empty.subtitle": "当前没有用户全局安装的 npm 包。",
        "nodeRepo.global.uninstall": "卸载",
        "nodeRepo.global.confirmUninstall": "卸载 %@？",
        "nodeRepo.global.confirmUninstallMessage": "将执行 `npm uninstall -g %@`。",
        "nodeRepo.cache.location": "缓存路径：",
        "nodeRepo.cache.sizeFormat": "大小：%@",
        "nodeRepo.cache.clean": "清理缓存",
        "nodeRepo.cache.confirmClean": "清理 npm 缓存？",
        "nodeRepo.cache.confirmCleanMessage": "将执行 `npm cache clean --force`。已下载的 tarball 需重新拉取。",
        "nodeRepo.cache.cleaned": "缓存已清理",
        "nodeRepo.npmMissing.title": "未检测到 npm",
        "nodeRepo.npmMissing.subtitle": "PATH 上未找到 `npm` 命令。请先在开发环境中安装 Node.js。",
        "nodeRepo.tab.globalPkg": "全局包",
        "nodeRepo.registry.presets": "预设镜像",
        "nodeRepo.registry.custom": "自定义 URL",
        "nodeRepo.registry.apply": "应用",
        "nodeRepo.registry.confirmApply": "确定要切换 npm registry 吗？",
        "nodeRepo.msg.saved": "已保存",
        "nodeRepo.msg.invalidURL": "URL 必须以 http:// 或 https:// 开头",
        "nodeRepo.pkg.uninstall": "卸载",
        "nodeRepo.pkg.confirmDelete": "确定要卸载该全局包吗？",
        "nodeRepo.pkg.empty": "未安装全局包",
        "nodeRepo.pkg.search": "搜索包名",
        "nodeRepo.pkg.total": "共 %d 个",
        "nodeRepo.cache.path": "缓存目录",
        "nodeRepo.cache.size": "缓存大小",

        "pythonRepo.title": "Python 仓库",
        "pythonRepo.subtitle": "管理 pip index-url、用户级包与 wheel 缓存",
        "pythonRepo.tab.index": "镜像源",
        "pythonRepo.tab.globalPkg": "用户包",
        "pythonRepo.tab.cache": "缓存",
        "pythonRepo.index.current": "当前 index：",
        "pythonRepo.index.presets": "预设镜像",
        "pythonRepo.index.custom": "自定义 URL",
        "pythonRepo.index.apply": "应用",
        "pythonRepo.index.confirmApply": "确定要切换 pip 镜像吗？",
        "pythonRepo.msg.saved": "已保存",
        "pythonRepo.msg.invalidURL": "URL 必须以 http:// 或 https:// 开头",
        "pythonRepo.pkg.uninstall": "卸载",
        "pythonRepo.pkg.confirmDelete": "确定要卸载该 Python 包吗？",
        "pythonRepo.pkg.empty": "未安装用户级 Python 包",
        "pythonRepo.pkg.search": "搜索包名",
        "pythonRepo.pkg.total": "共 %d 个",
        "pythonRepo.cache.path": "缓存目录",
        "pythonRepo.cache.size": "缓存大小",
        "pythonRepo.cache.clean": "清理缓存",
        "pythonRepo.cache.confirmClean": "清理 pip 缓存？",
        "pythonRepo.cache.cleaned": "缓存已清理",
        "pythonRepo.pipMissing.title": "未检测到 pip",
        "pythonRepo.pipMissing.subtitle": "PATH 上未找到 `pip3` 命令。请先在开发环境中安装 Python。",

        "nav.rubyRepo": "Ruby 全局环境",
        "nav.rustRepo": "Rust 全局环境",
        "nav.phpRepo": "PHP 全局环境",
        "nav.dotnetRepo": ".NET 全局环境",

        "rubyRepo.title": "Ruby 仓库",
        "rubyRepo.subtitle": "管理 RubyGems 镜像源、全局 Gem 与缓存",
        "rubyRepo.tab.source": "镜像源",
        "rubyRepo.tab.gems": "全局 Gem",
        "rubyRepo.tab.cache": "缓存",
        "rubyRepo.source.current": "当前源：",
        "rubyRepo.source.presets": "预设镜像",
        "rubyRepo.source.custom": "自定义 URL",
        "rubyRepo.source.apply": "应用",
        "rubyRepo.source.confirmApply": "确定要切换 RubyGems 源吗？",
        "rubyRepo.gem.uninstall": "卸载",
        "rubyRepo.gem.confirmDelete": "确定要卸载该全局 Gem 吗？",
        "rubyRepo.gem.empty": "未安装用户级 Gem",
        "rubyRepo.gem.search": "搜索 Gem 名称",
        "rubyRepo.gem.total": "共 %d 个",
        "rubyRepo.cache.confirmClean": "清理 Gem 缓存？",
        "rubyRepo.gemMissing.title": "未检测到 gem",
        "rubyRepo.gemMissing.subtitle": "PATH 上未找到 `gem` 命令。请先在开发环境中安装 Ruby。",

        "rustRepo.title": "Rust 仓库",
        "rustRepo.subtitle": "管理 Cargo 镜像、全局 Crate 与缓存",
        "rustRepo.tab.registry": "镜像源",
        "rustRepo.tab.crates": "全局 Crate",
        "rustRepo.tab.cache": "缓存",
        "rustRepo.registry.current": "当前源：",
        "rustRepo.registry.presets": "预设镜像",
        "rustRepo.registry.custom": "自定义 URL",
        "rustRepo.registry.apply": "应用",
        "rustRepo.registry.confirmApply": "确定要切换 Cargo 镜像吗？",
        "rustRepo.registry.hint": "配置写入 ~/.cargo/config.toml，替换默认 crates.io 镜像。",
        "rustRepo.crate.uninstall": "卸载",
        "rustRepo.crate.confirmDelete": "确定要卸载该 Crate 吗？",
        "rustRepo.crate.empty": "未安装用户级 Crate",
        "rustRepo.crate.search": "搜索 Crate 名称",
        "rustRepo.crate.total": "共 %d 个",
        "rustRepo.cache.confirmClean": "清理 Cargo 缓存？",
        "rustRepo.cargoMissing.title": "未检测到 cargo",
        "rustRepo.cargoMissing.subtitle": "PATH 上未找到 `cargo` 命令。请先在开发环境中安装 Rust。",

        "phpRepo.title": "PHP 仓库",
        "phpRepo.subtitle": "管理 Composer 镜像、全局包与缓存",
        "phpRepo.tab.repository": "镜像源",
        "phpRepo.tab.packages": "全局包",
        "phpRepo.tab.cache": "缓存",
        "phpRepo.repository.current": "当前源：",
        "phpRepo.repository.presets": "预设镜像",
        "phpRepo.repository.custom": "自定义 URL",
        "phpRepo.repository.apply": "应用",
        "phpRepo.repository.confirmApply": "确定要切换 Composer 镜像吗？",
        "phpRepo.pkg.uninstall": "卸载",
        "phpRepo.pkg.confirmDelete": "确定要卸载该全局包吗？",
        "phpRepo.pkg.empty": "未安装全局 Composer 包",
        "phpRepo.pkg.search": "搜索包名",
        "phpRepo.pkg.total": "共 %d 个",
        "phpRepo.cache.confirmClean": "清理 Composer 缓存？",
        "phpRepo.composerMissing.title": "未检测到 composer",
        "phpRepo.composerMissing.subtitle": "PATH 上未找到 `composer` 命令。请先安装 PHP 与 Composer。",

        "dotnetRepo.title": ".NET 仓库",
        "dotnetRepo.subtitle": "管理 NuGet 源、全局工具与缓存",
        "dotnetRepo.tab.source": "NuGet 源",
        "dotnetRepo.tab.tools": "全局工具",
        "dotnetRepo.tab.cache": "缓存",
        "dotnetRepo.source.enabled": "已启用源：",
        "dotnetRepo.source.none": "尚未配置 NuGet 源。",
        "dotnetRepo.source.presets": "预设源",
        "dotnetRepo.source.custom": "自定义源",
        "dotnetRepo.source.name": "名称",
        "dotnetRepo.source.apply": "添加/更新",
        "dotnetRepo.source.confirmApply": "确定要更新 NuGet 源吗？",
        "dotnetRepo.source.hint": "自定义源将写入用户级 NuGet.Config。",
        "dotnetRepo.tool.uninstall": "卸载",
        "dotnetRepo.tool.confirmDelete": "确定要卸载该全局工具吗？",
        "dotnetRepo.tool.empty": "未安装全局 .NET 工具",
        "dotnetRepo.tool.search": "搜索工具名称",
        "dotnetRepo.tool.total": "共 %d 个",
        "dotnetRepo.cache.confirmClean": "清理 NuGet 缓存？",
        "dotnetRepo.dotnetMissing.title": "未检测到 dotnet",
        "dotnetRepo.dotnetMissing.subtitle": "PATH 上未找到 `dotnet` 命令。请先在开发环境中安装 .NET SDK。",

        "common.refresh": "刷新",
        "common.cancel": "取消",
        "common.confirm": "确定",

        "settings.backups": "备份",
        "settings.backups.title": "配置文件备份",
        "settings.backups.subtitle": "EnvMatrix 修改配置文件前会自动生成的备份。你可以在这里一键还原或删除。",
        "settings.backups.empty": "暂无备份。通过 EnvMatrix 切换镜像或修改配置后，备份会自动出现在这里。",
        "settings.backups.column.file": "备份文件",
        "settings.backups.column.target": "目标",
        "settings.backups.column.time": "修改时间",
        "settings.backups.column.size": "大小",
        "settings.backups.restore": "还原",
        "settings.backups.delete": "删除",
        "settings.backups.reveal": "在 Finder 中显示",
        "settings.backups.confirmRestore": "还原此备份？这将覆盖 %@。",
        "settings.backups.confirmDelete": "确认删除该备份？此操作不可撤销。",
        "settings.backups.restoreSuccess": "已从备份还原 %@。",
        "settings.backups.deleteSuccess": "备份已删除。",
        "settings.backups.kind.npmrc": "npm 镜像 (.npmrc)",
        "settings.backups.kind.mavenSettings": "Maven settings.xml",

        "globalSearch.placeholder": "在包管理器中搜索…",
        "globalSearch.hint.title": "跨模块搜索",
        "globalSearch.hint.subtitle": "输入关键字，跨 Homebrew、Maven、Go 与 npm 快速定位。",
        "globalSearch.noResults": "没有匹配结果",
        "globalSearch.source.brew": "Homebrew",
        "globalSearch.source.maven": "Maven",
        "globalSearch.source.go": "Go",
        "globalSearch.source.node": "npm",
        "globalSearch.source.python": "pip",

        "settings.diagnostics": "诊断",
        "settings.diagnostics.title": "诊断报告",
        "settings.diagnostics.subtitle": "汇总当前机器的包管理状态，方便附加到 Issue。",
        "settings.diagnostics.generate": "生成报告",
        "settings.diagnostics.copy": "复制",
        "settings.diagnostics.save": "保存为 Markdown…",
        "settings.diagnostics.copied": "已复制到剪贴板",
        "settings.diagnostics.emptyHint": "点击「生成报告」以扫描 Homebrew / Maven / Go / npm 状态。",

        "settings.notifications": "通知",
        "settings.notifications.toggle": "长任务完成时发送系统通知",
        "settings.notifications.hint": "首次开启会请求 macOS 的通知权限；关闭后 EnvMatrix 不会再打扰你。",

        "notify.brew.success.title": "Homebrew 操作完成",
        "notify.brew.success.body": "brew %@ 已成功完成。",
        "notify.brew.failure.title": "Homebrew 操作失败",
        "notify.brew.failure.body": "brew %@ 未能完成，请查看输出日志。",
        "notify.npm.cache.title": "npm 缓存已清理",
        "notify.npm.cache.body": "本地 npm 缓存已经全部释放。",
        "notify.pip.cache.title": "pip 缓存已清理",
        "notify.pip.cache.body": "本地 pip 缓存已经全部释放。",

        "nav.projectEnv": "项目本地环境",
        "projenv.title": "项目环境",
        "projenv.subtitle": "已扫描 %d 个项目根目录",
        "projenv.scannedIn": "耗时 %.1f 秒",
        "projenv.total": "总计",
        "projenv.reclaimable": "可回收空间",
        "projenv.searchPlaceholder": "搜索项目或环境路径",
        "projenv.minSize": "最小体积",
        "projenv.minSizeOff": "不限",
        "projenv.roots": "根目录",
        "projenv.rescan": "重新扫描",
        "projenv.filter.all": "全部",
        "projenv.sort.menuLabel": "排序 (%@)",
        "projenv.sort.sizeDesc": "体积从大到小",
        "projenv.sort.sizeAsc": "体积从小到大",
        "projenv.sort.mtimeAsc": "最久未修改在前",
        "projenv.sort.mtimeDesc": "最近修改在前",
        "gradleCache.sort.sizeDesc": "体积从大到小",
        "gradleCache.sort.sizeAsc": "体积从小到大",
        "gradleCache.sort.mtimeDesc": "最近修改在前",
        "gradleCache.sort.mtimeAsc": "最久未修改在前",
        "gradleCache.title": "Gradle 全局缓存",
        "gradleCache.subtitle": "扫描 ~/.gradle/caches 与 ~/.gradle/wrapper/dists，安全回收依赖与 Wrapper 发行版",
        "gradleCache.section.artifacts": "依赖缓存 (modules-2)",
        "gradleCache.section.wrappers": "Wrapper 发行版",
        "gradleCache.total.artifacts": "依赖缓存合计",
        "gradleCache.total.wrappers": "Wrapper 合计",
        "gradleCache.total.combined": "总计",
        "gradleCache.searchPlaceholder.artifacts": "搜索 group:artifact 或版本",
        "gradleCache.searchPlaceholder.wrappers": "搜索 Gradle 版本",
        "gradleCache.column.groupArtifact": "Group : Artifact",
        "gradleCache.column.version": "版本",
        "gradleCache.column.size": "体积",
        "gradleCache.column.mtime": "最近修改",
        "gradleCache.action.reveal": "在 Finder 中显示",
        "gradleCache.action.delete": "移入回收站",
        "gradleCache.action.deleteSelected": "删除选中 (%d)",
        "gradleCache.empty.title": "未发现 Gradle 缓存",
        "gradleCache.empty.hint": "尚未在 ~/.gradle 下检测到依赖或 Wrapper。请先运行一次 Gradle 构建，或访问官网了解更多。",
        "gradleCache.empty.openWebsite": "打开 Gradle 官网",
        "gradleCache.confirmDelete.title": "确认移入回收站",
        "gradleCache.confirmDelete.body": "共 %d 项将被移入回收站，可稍后从访达恢复。",
        "gradleCache.confirmDelete.confirm": "移入回收站",
        "projenv.health.active": "活跃",
        "projenv.health.idle": "闲置",
        "projenv.health.abandoned": "疑似废弃",
        "projenv.overview.total": "总数",
        "projenv.overview.reclaimable": "可回收空间",
        "projenv.overview.abandonedCount": "废弃项数量",
        "projenv.overview.abandonedSize": "废弃项体积",
        "projenv.overview.cleanAbandoned": "清理所有废弃项",
        "projenv.toolbar.deleteSelected": "删除选中 (%d)",
        "projenv.multi.title": "已选 %1$d 项 · %2$@",
        "projenv.multi.subtitle": "路径预览",
        "projenv.multi.moreItems": "还有 %d 项…",
        "projenv.multi.deleteSelected": "删除选中",
        "projenv.batchDelete.title": "确认批量删除",
        "projenv.batchDelete.body": "将把 %1$d 个项目移入回收站，共 %2$@。",
        "projenv.batchDelete.confirm": "移入回收站",
        "projenv.batchDelete.morePaths": "还有 %d 条路径…",
        "projenv.abandonedCleanup.title": "清理所有废弃项",
        "projenv.abandonedCleanup.body": "将把 %1$d 个废弃项目移入回收站，共 %2$@。",
        "projenv.abandonedCleanup.confirm": "全部清理",
        "projenv.abandonedCleanup.morePaths": "还有 %d 条路径…",
        "projenv.rootsEditor.includeXcode": "扫描 Xcode DerivedData",
        "projenv.kind.rustTarget": "Rust target",
        "projenv.kind.xcodeDerivedData": "Xcode DerivedData",
        "projenv.kind.gradleCache": "Gradle 缓存",
        "projenv.kind.mavenTarget": "Maven target",
        "projenv.action.reveal": "在访达中显示",
        "projenv.action.revealProject": "定位项目",
        "projenv.action.openTerminal": "在终端中打开",
        "projenv.action.reinstall": "重新安装",
        "projenv.action.delete": "移到废纸篓",
        "projenv.actions": "操作",
        "projenv.trashHint": "删除会将目标文件夹移动到废纸篓，如有需要可从废纸篓恢复。",
        "projenv.detail.pickHint": "在左侧选择一个项目环境以查看详情。",
        "projenv.field.projectRoot": "项目根目录",
        "projenv.field.envPath": "环境路径",
        "projenv.field.size": "大小",
        "projenv.field.pythonVersion": "Python 版本",
        "projenv.field.packageManager": "包管理器",
        "projenv.field.modified": "修改时间",
        "projenv.pm.unknown": "未知",
        "projenv.deleteConfirm.title": "移到废纸篓？",
        "projenv.deleteConfirm.body": "将会把以下文件夹移动到废纸篓：\n\n%@\n\n大小：%@\n\n如有需要可从废纸篓恢复。",
        "projenv.deleteConfirm.confirm": "移到废纸篓",
        "projenv.cancel": "取消",
        "projenv.done": "完成",
        "projenv.rootsEditor.title": "项目根目录",
        "projenv.rootsEditor.hint": "添加你存放项目的目录，EnvMatrix 将递归扫描（有深度限制）以查找 venv 与 node_modules。",
        "projenv.rootsEditor.add": "添加根目录",
        "projenv.log.title": "操作日志",
        "projenv.scanning": "正在扫描项目根目录…",
        "projenv.empty.noRoots": "尚未配置项目根目录，添加一个以开始扫描。",
        "projenv.empty.noEnvs": "配置的根目录下未发现任何项目环境。"
    ]
}
