import Foundation

extension L10n {
    static let enNavigation: [String: String] = [
        "app.name": "EnvMatrix",
        "app.welcome.title": "Welcome to EnvMatrix",
        "app.welcome.subtitle": "Select an item from the sidebar to get started.",
        "app.underConstruction": "This section is under construction.",

        "nav.overview": "Overview",
        "nav.devEnvironments": "Dev Environments",
        "nav.packages": "Packages",
        "nav.packagesSystem": "System Packages",
        "nav.packagesLangs": "Language Globals",
        "nav.projectEnvGroup": "Project Environments",
        "nav.aiEnvironments": "AI Environments",
        "nav.system": "System",
        "nav.dashboard": "Dashboard",
        "nav.homebrew": "Homebrew",
        "nav.mavenRepo": "Java Global",
        "nav.skills": "Skills",
        "nav.aiCLI": "AI CLI",
        "nav.mcpServers": "MCP Servers",
        "nav.settings": "Settings",
        "nav.shellEnv": "Shell Environment",
        "nav.hosts": "Hosts",
        "nav.localApps": "Local Apps",
        "nav.goRepo": "Go Global",
        "nav.nodeRepo": "Node Global",
        "nav.pythonRepo": "Python Global",
        "nav.rubyRepo": "Ruby Global",
        "nav.rustRepo": "Rust Global",
        "nav.phpRepo": "PHP Global",
        "nav.dotnetRepo": ".NET Global",
        "nav.uvRepo": "uv Global",
        "nav.pnpmRepo": "pnpm Global",
        "nav.projectEnv": "Project Environments",

        "common.refresh": "Refresh",
        "common.cancel": "Cancel",
        "common.confirm": "Confirm",

        "globalSearch.placeholder": "Search across package managers…",
        "globalSearch.hint.title": "Search everything",
        "globalSearch.hint.subtitle": "Type to search Homebrew, Maven, Go modules and global npm packages at once.",
        "globalSearch.noResults": "No matching results",
        "globalSearch.source.brew": "Homebrew",
        "globalSearch.source.maven": "Maven",
        "globalSearch.source.go": "Go",
        "globalSearch.source.node": "npm",
        "globalSearch.source.python": "pip"
    ]

    static let zhNavigation: [String: String] = [
        "app.name": "EnvMatrix",
        "app.welcome.title": "欢迎使用 EnvMatrix",
        "app.welcome.subtitle": "请从左侧边栏选择一项以开始使用。",
        "app.underConstruction": "此模块正在建设中。",

        "nav.overview": "概览",
        "nav.devEnvironments": "开发环境",
        "nav.packages": "包管理",
        "nav.packagesSystem": "系统包管理",
        "nav.packagesLangs": "语言全局环境",
        "nav.projectEnvGroup": "项目本地环境",
        "nav.aiEnvironments": "AI 环境",
        "nav.system": "系统",
        "nav.dashboard": "仪表盘",
        "nav.homebrew": "Homebrew",
        "nav.mavenRepo": "Java 全局环境",
        "nav.skills": "技能",
        "nav.aiCLI": "AI 命令行",
        "nav.mcpServers": "MCP 服务器",
        "nav.settings": "设置",
        "nav.shellEnv": "Shell 本地环境",
        "nav.hosts": "Hosts 管理",
        "nav.localApps": "本地应用",
        "nav.goRepo": "Go 全局环境",
        "nav.nodeRepo": "Node 全局环境",
        "nav.pythonRepo": "Python 全局环境",
        "nav.rubyRepo": "Ruby 全局环境",
        "nav.rustRepo": "Rust 全局环境",
        "nav.phpRepo": "PHP 全局环境",
        "nav.dotnetRepo": ".NET 全局环境",
        "nav.uvRepo": "uv 全局环境",
        "nav.pnpmRepo": "pnpm 全局环境",
        "nav.projectEnv": "项目本地环境",

        "common.refresh": "刷新",
        "common.cancel": "取消",
        "common.confirm": "确定",

        "globalSearch.placeholder": "在包管理器中搜索…",
        "globalSearch.hint.title": "跨模块搜索",
        "globalSearch.hint.subtitle": "输入关键字，跨 Homebrew、Maven、Go 与 npm 快速定位。",
        "globalSearch.noResults": "没有匹配结果",
        "globalSearch.source.brew": "Homebrew",
        "globalSearch.source.maven": "Maven",
        "globalSearch.source.go": "Go",
        "globalSearch.source.node": "npm",
        "globalSearch.source.python": "pip"
    ]
}
