import Foundation

extension L10n {
    static let enContainer: [String: String] = [
        "nav.containerContexts": "Container Contexts",
        "globalSearch.source.containerContext": "Containers",
        "container.title": "Container Contexts",
        "container.subtitle": "Manage Docker contexts and Podman connections in one place.",
        "container.docker.section": "Docker Contexts",
        "container.podman.section": "Podman Connections",
        "container.docker.empty": "No Docker contexts found. Click + to add one.",
        "container.podman.empty": "No Podman connections found. Click + to add one.",
        "container.error.cliMissing": "CLI not detected. Install it with brew and try again.",
        "container.badge.builtIn": "built-in",
        "container.badge.tls": "TLS",
        "container.badge.ssh": "SSH",
        "container.action.use": "Use",
        "container.action.ping": "Ping",
        "container.action.edit": "Edit",
        "container.action.delete": "Delete",
        "container.action.add": "Add",
        "container.action.refresh": "Refresh",
        "container.delete.protectedTooltip": "Built-in context cannot be removed.",
        "container.editor.name": "Name",
        "container.editor.endpoint": "Endpoint scheme",
        "container.editor.host": "Host",
        "container.editor.description": "Description",
        "container.editor.tls": "TLS",
        "container.editor.caCert": "CA certificate path",
        "container.editor.clientCert": "Client certificate path",
        "container.editor.clientKey": "Client key path",
        "container.editor.skipTLSVerify": "Skip TLS verification",
        "container.editor.uri": "URI",
        "container.editor.identity": "SSH identity file",
        "container.editor.makeDefault": "Set as default",
        "container.editor.cancel": "Cancel",
        "container.editor.save": "Save",
        "container.docker.editor.addTitle": "Add Docker Context",
        "container.docker.editor.editTitle": "Edit Docker Context",
        "container.podman.editor.addTitle": "Add Podman Connection",
        "container.podman.editor.editTitle": "Edit Podman Connection",
        "container.podman.defaultInvalidated": "Current default connection has been removed. Please set a new default."
    ]

    static let zhContainer: [String: String] = [
        "nav.containerContexts": "容器上下文",
        "globalSearch.source.containerContext": "容器上下文",
        "container.title": "容器上下文",
        "container.subtitle": "统一管理 Docker 上下文与 Podman 远程连接。",
        "container.docker.section": "Docker 上下文",
        "container.podman.section": "Podman 连接",
        "container.docker.empty": "尚未发现 Docker 上下文，点击 + 添加。",
        "container.podman.empty": "尚未发现 Podman 连接，点击 + 添加。",
        "container.error.cliMissing": "未检测到 CLI，请先使用 brew 安装后重试。",
        "container.badge.builtIn": "内置",
        "container.badge.tls": "TLS",
        "container.badge.ssh": "SSH",
        "container.action.use": "切换",
        "container.action.ping": "连通性检测",
        "container.action.edit": "编辑",
        "container.action.delete": "删除",
        "container.action.add": "新增",
        "container.action.refresh": "刷新",
        "container.delete.protectedTooltip": "内置上下文不可删除。",
        "container.editor.name": "名称",
        "container.editor.endpoint": "协议",
        "container.editor.host": "主机地址",
        "container.editor.description": "描述",
        "container.editor.tls": "TLS 选项",
        "container.editor.caCert": "CA 证书路径",
        "container.editor.clientCert": "客户端证书路径",
        "container.editor.clientKey": "客户端密钥路径",
        "container.editor.skipTLSVerify": "跳过 TLS 校验",
        "container.editor.uri": "URI",
        "container.editor.identity": "SSH 私钥文件",
        "container.editor.makeDefault": "设为默认",
        "container.editor.cancel": "取消",
        "container.editor.save": "保存",
        "container.docker.editor.addTitle": "新增 Docker 上下文",
        "container.docker.editor.editTitle": "编辑 Docker 上下文",
        "container.podman.editor.addTitle": "新增 Podman 连接",
        "container.podman.editor.editTitle": "编辑 Podman 连接",
        "container.podman.defaultInvalidated": "默认连接已被删除，请重新指定默认连接。"
    ]
}
