import Foundation

extension L10n {
    static let enDashboard: [String: String] = [
        "dashboard.title": "Dashboard",
        "dashboard.subtitle": "Overview of your local dev & AI environments",
        "dashboard.refresh": "Refresh",
        "dashboard.runtimeSuffix": "Runtime",
        "dashboard.current": "Current",
        "dashboard.notSet": "Not Set",
        "dashboard.system": "System",
        "dashboard.installed": "installed",
        "dashboard.configured": "configured",
        "dashboard.storage": "Storage",
        "dashboard.skills": "Skills",
        "dashboard.mcpServers": "MCP Servers",
        "dashboard.activeRuntimes": "Active Runtimes",
        "dashboard.managed": "Managed",
        "dashboard.section.runtimes": "Runtimes",
        "dashboard.section.overview": "Overview",
        "dashboard.section.packages": "Package Managers",
        "dashboard.packages.refresh": "Rescan package caches",
        "dashboard.package.cacheSize": "Cache size",
        "dashboard.package.needsCleanup": "Consider cleaning up",
        "dashboard.attention": "Needs attention",
        "dashboard.storage.subtitle": "Used by managed versions",
        "dashboard.card.openHint": "Open details",
        "dashboard.section.containers": "Containers",
        "dashboard.section.attention": "Needs attention",
        "dashboard.attention.allClear": "Everything looks good",
        "dashboard.attention.allClear.detail": "PATH is configured, caches are under %@ and you are on the latest version.",
        "dashboard.attention.shims.title": "Terminal won't see switched runtimes",
        "dashboard.attention.shims.detail": "~/.envmatrix/shims is not on PATH. Add it to %@ to make \"Set Active\" take effect.",
        "dashboard.attention.shims.action": "Add to %@",
        "dashboard.attention.cache.title": "%@ cache is %@",
        "dashboard.attention.cache.detail": "Above the %@ cleanup threshold. Review and clean it from the %@ page.",
        "dashboard.attention.cache.action": "Open",
        "dashboard.attention.update.title": "EnvMatrix %@ is available",
        "dashboard.attention.update.detail": "You are running %@. Release notes and downloads are on GitHub.",
        "dashboard.attention.update.action": "View release"
    ]

    static let zhDashboard: [String: String] = [
        "dashboard.title": "仪表盘",
        "dashboard.subtitle": "本地开发和 AI 环境的总览",
        "dashboard.refresh": "刷新",
        "dashboard.runtimeSuffix": "运行时",
        "dashboard.current": "当前",
        "dashboard.notSet": "未设置",
        "dashboard.system": "系统",
        "dashboard.installed": "已安装",
        "dashboard.configured": "已配置",
        "dashboard.storage": "存储",
        "dashboard.skills": "技能",
        "dashboard.mcpServers": "MCP 服务器",
        "dashboard.activeRuntimes": "已启用运行时",
        "dashboard.managed": "已托管",
        "dashboard.section.runtimes": "运行时",
        "dashboard.section.overview": "总览",
        "dashboard.section.packages": "包管理器",
        "dashboard.packages.refresh": "重新扫描包缓存",
        "dashboard.package.cacheSize": "缓存占用",
        "dashboard.package.needsCleanup": "建议清理",
        "dashboard.attention": "需要关注",
        "dashboard.storage.subtitle": "托管版本占用",
        "dashboard.card.openHint": "打开详情",
        "dashboard.section.containers": "容器",
        "dashboard.section.attention": "需要关注",
        "dashboard.attention.allClear": "一切正常",
        "dashboard.attention.allClear.detail": "PATH 已配置，各缓存均低于 %@，并且已是最新版本。",
        "dashboard.attention.shims.title": "终端还看不到切换后的运行时",
        "dashboard.attention.shims.detail": "~/.envmatrix/shims 不在 PATH 中。把它写入 %@ 后，“设为活动”才会生效。",
        "dashboard.attention.shims.action": "写入 %@",
        "dashboard.attention.cache.title": "%@ 缓存已达 %@",
        "dashboard.attention.cache.detail": "超过 %@ 的清理阈值，建议到 %@ 页面查看并清理。",
        "dashboard.attention.cache.action": "打开",
        "dashboard.attention.update.title": "EnvMatrix %@ 已发布",
        "dashboard.attention.update.detail": "当前版本 %@。更新日志与下载见 GitHub。",
        "dashboard.attention.update.action": "查看发布页"
    ]
}
