import Foundation

extension L10n {
    static let zh: [String: String] = [
        "app.name": "EnvMatrix",
        "app.welcome.title": "欢迎使用 EnvMatrix",
        "app.welcome.subtitle": "请从左侧边栏选择一项以开始使用。",
        "app.underConstruction": "此模块正在建设中。",

        "nav.overview": "概览",
        "nav.devEnvironments": "开发环境",
        "nav.packages": "包管理",
        "nav.aiEnvironments": "AI 环境",
        "nav.system": "系统",
        "nav.dashboard": "仪表盘",
        "nav.homebrew": "Homebrew",
        "nav.mavenRepo": "Maven 仓库",
        "nav.skills": "技能",
        "nav.aiCLI": "AI 命令行",
        "nav.mcpServers": "MCP 服务器",
        "nav.settings": "设置",

        "dashboard.title": "仪表盘",
        "dashboard.subtitle": "本地开发和 AI 环境的总览",
        "dashboard.refresh": "刷新",
        "dashboard.runtimeSuffix": "运行时",
        "dashboard.current": "当前",
        "dashboard.notSet": "未设置",
        "dashboard.system": "系统",
        "dashboard.installed": "已安装",
        "dashboard.configured": "已配置",
        "dashboard.storage": "存储",
        "dashboard.skills": "技能",
        "dashboard.mcpServers": "MCP 服务器",
        "dashboard.activeRuntimes": "已启用运行时",
        "dashboard.managed": "已托管",
        "dashboard.section.runtimes": "运行时",
        "dashboard.section.overview": "总览",
        "dashboard.section.packages": "包管理器",
        "dashboard.package.cacheSize": "缓存占用",
        "dashboard.package.needsCleanup": "建议清理",
        "dashboard.attention": "需要关注",
        "dashboard.storage.subtitle": "托管版本占用",
        "dashboard.card.openHint": "打开详情",

        "runtime.installed": "已安装",
        "runtime.available": "可用版本",
        "runtime.active": "当前",
        "runtime.none": "无",
        "runtime.systemDefault": "系统默认",
        "runtime.refresh": "刷新",
        "runtime.loading": "正在加载版本...",
        "runtime.noAvailable": "没有可用版本。",
        "runtime.noInstalled": "尚未安装任何版本。切换到\"可用版本\"进行安装。",
        "runtime.install": "安装",
        "runtime.installedLabel": "已安装",
        "runtime.setActive": "设为活动",
        "runtime.uninstall": "卸载",
        "runtime.uninstallTitle": "卸载 %@?",
        "runtime.cancel": "取消",
        "runtime.revealInFinder": "在访达中显示",
        "runtime.uninstallSystemMessage": "EnvMatrix 将删除以下文件夹:\n%@\n\n如果它是通过 brew / sdkman / nvm / pkg 安装的，使用其自带的卸载工具会更安全。系统所属的路径可能需要 sudo 权限，将被拒绝。",
        "runtime.uninstallMessage": "此操作将从系统中移除 %@ %@。",
        "runtime.uninstallSystemTooltip": "卸载此系统运行时（删除前会二次确认）",
        "runtime.uninstallTooltip": "卸载此版本",
        "runtime.systemBadge": "系统",

        "skills.title": "技能",
        "skills.refresh": "刷新",
        "skills.empty.title": "未找到技能",
        "skills.empty.subtitle": "配置的技能目录为空。",
        "skills.revealInFinder": "在访达中显示",
        "skills.delete": "删除",

        "cli.title": "AI 命令行",
        "cli.save": "保存",
        "cli.selectPrompt": "请选择一个 CLI 配置",
        "cli.selectHint": "在左侧选择一项配置以编辑其内容。",
        "cli.model": "模型",
        "cli.apiBaseURL": "API 基础地址",
        "cli.apiKey": "API 密钥",

        "mcp.title": "MCP 服务器",
        "mcp.add": "添加",
        "mcp.refresh": "刷新",
        "mcp.empty.title": "暂无 MCP 服务器",
        "mcp.empty.subtitle": "点击\"添加\"以配置新的服务器。",
        "mcp.edit": "编辑",
        "mcp.delete": "删除",
        "mcp.argCount.one": "%d 个参数",
        "mcp.argCount.many": "%d 个参数",
        "mcp.editor.editTitle": "编辑 MCP 服务器",
        "mcp.editor.addTitle": "添加 MCP 服务器",
        "mcp.editor.basics": "基本信息",
        "mcp.editor.name": "名称",
        "mcp.editor.command": "命令",
        "mcp.editor.arguments": "参数",
        "mcp.editor.argsPlaceholder": "以逗号分隔",
        "mcp.editor.argsHelp": "多个值用英文逗号分隔，例如: --port,8080",
        "mcp.editor.envVars": "环境变量",
        "mcp.editor.envKey": "键",
        "mcp.editor.envValue": "值",
        "mcp.editor.addVariable": "添加变量",
        "mcp.editor.cancel": "取消",
        "mcp.editor.save": "保存",

        "settings.general": "通用",
        "settings.logs": "日志",
        "settings.about": "关于",
        "settings.appearance": "外观",
        "settings.colorScheme": "配色方案",
        "settings.system": "跟随系统",
        "settings.light": "浅色",
        "settings.dark": "深色",
        "settings.language": "语言",
        "settings.languageLabel": "界面语言",
        "settings.mirrors": "镜像源",
        "settings.nodeMirror": "Node.js 镜像",
        "settings.pythonMirror": "Python 镜像",
        "settings.goMirror": "Go 镜像",
        "settings.javaMirror": "Java 镜像",
        "settings.resetDefaults": "恢复默认",
        "settings.entries": "共 %d 条",
        "settings.clear": "清除",
        "settings.noLogs": "暂无日志。",
        "settings.version": "版本 %@",
        "settings.aboutDescription": "一款统一的 macOS 控制面板，用于管理开发者运行时和 AI 开发环境。",
        "settings.viewGitHub": "在 GitHub 上查看",

        "brew.title": "Homebrew",
        "brew.notInstalled.title": "未找到 Homebrew",
        "brew.notInstalled.subtitle": "EnvMatrix 在 /opt/homebrew/bin/brew 或 /usr/local/bin/brew 未找到 brew 可执行文件。请先安装 Homebrew。",
        "brew.formulae": "Formula",
        "brew.casks": "Cask",
        "brew.refresh": "刷新",
        "brew.loading": "正在加载 Homebrew 清单…",
        "brew.emptyList": "当前筛选条件下没有匹配的包。",
        "brew.searchPlaceholder": "搜索名称或描述",
        "brew.outdatedCount": "%d 个可升级",
        "brew.upgradeAll": "全部升级",
        "brew.cleanup": "清理缓存",
        "brew.update": "更新元数据",
        "brew.filter.outdatedOnly": "仅显示可升级",
        "brew.filter.requestedOnly": "仅显示手动安装",
        "brew.action.upgrade": "升级",
        "brew.action.uninstall": "卸载",
        "brew.action.pin": "锁定版本",
        "brew.action.unpin": "解锁版本",
        "brew.action.openHomepage": "打开主页",
        "brew.detail.selectHint": "在左侧选择一个包以查看详情。",
        "brew.detail.kind": "类型",
        "brew.detail.installedVersion": "已安装",
        "brew.detail.latestVersion": "最新版本",
        "brew.detail.homepage": "主页",
        "brew.detail.autoUpdates": "自动更新",
        "brew.detail.installedAt": "安装时间",
        "brew.detail.deprecationReason": "废弃原因",
        "brew.detail.dependencies": "依赖",
        "brew.yes": "是",
        "brew.no": "否",

        "mavenRepo.title": "Maven 仓库",
        "mavenRepo.subtitle": "管理 settings.xml 镜像与本地 ~/.m2/repository 依赖",
        "mavenRepo.refresh": "刷新",
        "mavenRepo.addPreset": "添加预设",
        "mavenRepo.settingsFile": "settings.xml：",
        "mavenRepo.localRepository": "本地仓库：",
        "mavenRepo.active": "已启用",
        "mavenRepo.mirrorOfFormat": "mirrorOf：%@",
        "mavenRepo.empty.title": "尚未配置镜像",
        "mavenRepo.empty.subtitle": "点击右上角 + 号添加预设镜像（阿里云 / 腾讯云 / 华为云 / 网易）。",
        "mavenRepo.tab.mirrors": "镜像源",
        "mavenRepo.tab.localArtifacts": "本地依赖",
        "mavenRepo.artifact.searchPlaceholder": "搜索 groupId、artifactId 或 version",
        "mavenRepo.artifact.countFormat": "共 %d 个依赖",
        "mavenRepo.artifact.totalSizeFormat": "总计：%@",
        "mavenRepo.artifact.versionCountFormat": "%d 个版本",
        "mavenRepo.artifact.sortByName": "按名称排序",
        "mavenRepo.artifact.sortBySize": "按大小排序",
        "mavenRepo.artifact.sortByModified": "按修改时间排序",
        "mavenRepo.artifact.ascending": "升序",
        "mavenRepo.artifact.loading": "正在扫描本地仓库…",
        "mavenRepo.artifact.notFound.title": "未找到本地仓库",
        "mavenRepo.artifact.notFound.subtitle": "路径 %@ 不存在。\n\n请先运行一次 Maven 构建以生成 ~/.m2/repository。",
        "mavenRepo.artifact.empty.title": "暂无依赖",
        "mavenRepo.artifact.empty.subtitle": "当前搜索条件下没有下载的依赖。",
        "mavenRepo.artifact.deleteAll": "删除所有版本",
        "mavenRepo.artifact.confirmDelete": "删除 %@？",
        "mavenRepo.artifact.confirmDeleteVersion": "删除 %@（%@）？",
        "mavenRepo.artifact.confirmDeleteMessage": "此操作将从磁盘移除 %@，无法撤销。",

        "nav.goRepo": "Go 仓库",
        "nav.nodeRepo": "Node 仓库",
        "goRepo.title": "Go 仓库",
        "goRepo.subtitle": "管理 GOPROXY 镜像并清理本地 GOMODCACHE",
        "goRepo.tab.proxy": "GOPROXY",
        "goRepo.tab.localCache": "本地模块",
        "goRepo.proxy.current": "当前 GOPROXY：",
        "goRepo.proxy.applyPreset": "应用预设",
        "goRepo.proxy.customPlaceholder": "自定义 GOPROXY（英文逗号分隔）",
        "goRepo.proxy.save": "保存",
        "goRepo.proxy.saved": "GOPROXY 已更新",
        "goRepo.cache.searchPlaceholder": "搜索模块或版本",
        "goRepo.cache.countFormat": "共 %d 个模块",
        "goRepo.cache.totalSizeFormat": "总计：%@",
        "goRepo.cache.versionCountFormat": "%d 个版本",
        "goRepo.cache.sortByName": "按名称排序",
        "goRepo.cache.sortBySize": "按大小排序",
        "goRepo.cache.sortByModified": "按修改时间排序",
        "goRepo.cache.ascending": "升序",
        "goRepo.cache.loading": "正在扫描 GOMODCACHE…",
        "goRepo.cache.notFound.title": "未找到 GOMODCACHE",
        "goRepo.cache.notFound.subtitle": "路径 %@ 不存在。\n\n请先执行一次 Go 构建以生成模块缓存。",
        "goRepo.cache.empty.title": "暂无模块",
        "goRepo.cache.empty.subtitle": "当前搜索条件下没有下载的模块。",
        "goRepo.cache.deleteAll": "删除所有版本",
        "goRepo.cache.confirmDelete": "删除 %@？",
        "goRepo.cache.confirmDeleteVersion": "删除 %@（%@）？",
        "goRepo.cache.confirmDeleteMessage": "此操作将从磁盘移除 %@，无法撤销。",
        "goRepo.goMissing.title": "未检测到 Go",
        "goRepo.goMissing.subtitle": "PATH 上未找到 `go` 命令。请先在开发环境中安装 Go。",
        "nodeRepo.title": "Node 仓库",
        "nodeRepo.subtitle": "管理 npm 镜像、全局包与缓存",
        "nodeRepo.tab.registry": "镜像",
        "nodeRepo.tab.global": "全局包",
        "nodeRepo.tab.cache": "缓存",
        "nodeRepo.registry.current": "当前镜像：",
        "nodeRepo.registry.applyPreset": "应用预设",
        "nodeRepo.registry.customPlaceholder": "自定义镜像 URL",
        "nodeRepo.registry.save": "保存",
        "nodeRepo.registry.saved": "镜像已更新",
        "nodeRepo.registry.confirmTitle": "更新 npm 镜像？",
        "nodeRepo.registry.confirmMessage": "~/.npmrc 中的 registry 将改为 %@，并生成备份 ~/.npmrc.envmatrix.bak。",
        "nodeRepo.global.searchPlaceholder": "搜索包名",
        "nodeRepo.global.countFormat": "共 %d 个包",
        "nodeRepo.global.loading": "正在加载全局包…",
        "nodeRepo.global.empty.title": "暂无全局包",
        "nodeRepo.global.empty.subtitle": "当前没有用户全局安装的 npm 包。",
        "nodeRepo.global.uninstall": "卸载",
        "nodeRepo.global.confirmUninstall": "卸载 %@？",
        "nodeRepo.global.confirmUninstallMessage": "将执行 `npm uninstall -g %@`。",
        "nodeRepo.cache.location": "缓存路径：",
        "nodeRepo.cache.sizeFormat": "大小：%@",
        "nodeRepo.cache.clean": "清理缓存",
        "nodeRepo.cache.confirmClean": "清理 npm 缓存？",
        "nodeRepo.cache.confirmCleanMessage": "将执行 `npm cache clean --force`。已下载的 tarball 需重新拉取。",
        "nodeRepo.cache.cleaned": "缓存已清理",
        "nodeRepo.npmMissing.title": "未检测到 npm",
        "nodeRepo.npmMissing.subtitle": "PATH 上未找到 `npm` 命令。请先在开发环境中安装 Node.js。",
        "nodeRepo.tab.globalPkg": "全局包",
        "nodeRepo.registry.presets": "预设镜像",
        "nodeRepo.registry.custom": "自定义 URL",
        "nodeRepo.registry.apply": "应用",
        "nodeRepo.registry.confirmApply": "确定要切换 npm registry 吗？",
        "nodeRepo.msg.saved": "已保存",
        "nodeRepo.msg.invalidURL": "URL 必须以 http:// 或 https:// 开头",
        "nodeRepo.pkg.uninstall": "卸载",
        "nodeRepo.pkg.confirmDelete": "确定要卸载该全局包吗？",
        "nodeRepo.pkg.empty": "未安装全局包",
        "nodeRepo.pkg.search": "搜索包名",
        "nodeRepo.pkg.total": "共 %d 个",
        "nodeRepo.cache.path": "缓存目录",
        "nodeRepo.cache.size": "缓存大小",
        "common.refresh": "刷新",
        "common.cancel": "取消",
        "common.confirm": "确定",

        "settings.backups": "备份",
        "settings.backups.title": "配置文件备份",
        "settings.backups.subtitle": "EnvMatrix 修改配置文件前会自动生成的备份。你可以在这里一键还原或删除。",
        "settings.backups.empty": "暂无备份。通过 EnvMatrix 切换镜像或修改配置后，备份会自动出现在这里。",
        "settings.backups.column.file": "备份文件",
        "settings.backups.column.target": "目标",
        "settings.backups.column.time": "修改时间",
        "settings.backups.column.size": "大小",
        "settings.backups.restore": "还原",
        "settings.backups.delete": "删除",
        "settings.backups.reveal": "在 Finder 中显示",
        "settings.backups.confirmRestore": "还原此备份？这将覆盖 %@。",
        "settings.backups.confirmDelete": "确认删除该备份？此操作不可撤销。",
        "settings.backups.restoreSuccess": "已从备份还原 %@。",
        "settings.backups.deleteSuccess": "备份已删除。",
        "settings.backups.kind.npmrc": "npm 镜像 (.npmrc)",
        "settings.backups.kind.mavenSettings": "Maven settings.xml"
    ]
}
