import Foundation

extension L10n {
    static let enPackagesExtra: [String: String] = [
        "rubyRepo.title": "Ruby Repository",
        "rubyRepo.subtitle": "Manage RubyGems sources, global gems and cache",
        "rubyRepo.tab.source": "Source",
        "rubyRepo.tab.gems": "Global Gems",
        "rubyRepo.tab.cache": "Cache",
        "rubyRepo.source.current": "Current source:",
        "rubyRepo.source.presets": "Preset sources",
        "rubyRepo.source.custom": "Custom URL",
        "rubyRepo.source.apply": "Apply",
        "rubyRepo.source.confirmApply": "Switch the RubyGems source?",
        "rubyRepo.gem.uninstall": "Uninstall",
        "rubyRepo.gem.confirmDelete": "Uninstall this global gem?",
        "rubyRepo.gem.empty": "No user-level gems installed",
        "rubyRepo.gem.search": "Search gems",
        "rubyRepo.gem.total": "%d total",
        "rubyRepo.cache.confirmClean": "Clean gem cache?",
        "rubyRepo.gemMissing.title": "gem Not Found",
        "rubyRepo.gemMissing.subtitle": "The `gem` command is not on PATH. Install Ruby from EnvMatrix Dev Environments first.",

        "rustRepo.title": "Rust Repository",
        "rustRepo.subtitle": "Manage Cargo registries, global crates and cache",
        "rustRepo.tab.registry": "Registry",
        "rustRepo.tab.crates": "Global Crates",
        "rustRepo.tab.cache": "Cache",
        "rustRepo.registry.current": "Current source:",
        "rustRepo.registry.presets": "Preset registries",
        "rustRepo.registry.custom": "Custom URL",
        "rustRepo.registry.apply": "Apply",
        "rustRepo.registry.confirmApply": "Switch the Cargo registry mirror?",
        "rustRepo.registry.hint": "Configuration is written to ~/.cargo/config.toml as a crates.io replacement.",
        "rustRepo.crate.uninstall": "Uninstall",
        "rustRepo.crate.confirmDelete": "Uninstall this crate?",
        "rustRepo.crate.empty": "No user-level crates installed",
        "rustRepo.crate.search": "Search crates",
        "rustRepo.crate.total": "%d total",
        "rustRepo.cache.confirmClean": "Clean Cargo cache?",
        "rustRepo.cargoMissing.title": "cargo Not Found",
        "rustRepo.cargoMissing.subtitle": "The `cargo` command is not on PATH. Install Rust from EnvMatrix Dev Environments first.",

        "phpRepo.title": "PHP Repository",
        "phpRepo.subtitle": "Manage Composer mirrors, global packages and cache",
        "phpRepo.tab.repository": "Repository",
        "phpRepo.tab.packages": "Global Packages",
        "phpRepo.tab.cache": "Cache",
        "phpRepo.repository.current": "Current source:",
        "phpRepo.repository.presets": "Preset mirrors",
        "phpRepo.repository.custom": "Custom URL",
        "phpRepo.repository.apply": "Apply",
        "phpRepo.repository.confirmApply": "Switch the Composer mirror?",
        "phpRepo.pkg.uninstall": "Uninstall",
        "phpRepo.pkg.confirmDelete": "Uninstall this global package?",
        "phpRepo.pkg.empty": "No global Composer packages installed",
        "phpRepo.pkg.search": "Search packages",
        "phpRepo.pkg.total": "%d total",
        "phpRepo.cache.confirmClean": "Clean Composer cache?",
        "phpRepo.composerMissing.title": "composer Not Found",
        "phpRepo.composerMissing.subtitle": "The `composer` command is not on PATH. Install PHP and Composer first.",

        "dotnetRepo.title": ".NET Repository",
        "dotnetRepo.subtitle": "Manage NuGet sources, global tools and cache",
        "dotnetRepo.tab.source": "NuGet Sources",
        "dotnetRepo.tab.tools": "Global Tools",
        "dotnetRepo.tab.cache": "Cache",
        "dotnetRepo.source.enabled": "Enabled sources:",
        "dotnetRepo.source.none": "No NuGet sources configured.",
        "dotnetRepo.source.presets": "Preset sources",
        "dotnetRepo.source.custom": "Custom source",
        "dotnetRepo.source.name": "Name",
        "dotnetRepo.source.apply": "Add/Update",
        "dotnetRepo.source.confirmApply": "Update NuGet sources?",
        "dotnetRepo.source.hint": "Custom sources are written to the user-level NuGet.Config.",
        "dotnetRepo.tool.uninstall": "Uninstall",
        "dotnetRepo.tool.confirmDelete": "Uninstall this global tool?",
        "dotnetRepo.tool.empty": "No global .NET tools installed",
        "dotnetRepo.tool.search": "Search tools",
        "dotnetRepo.tool.total": "%d total",
        "dotnetRepo.cache.confirmClean": "Clean NuGet cache?",
        "dotnetRepo.dotnetMissing.title": "dotnet Not Found",
        "dotnetRepo.dotnetMissing.subtitle": "The `dotnet` command is not on PATH. Install .NET SDK from EnvMatrix Dev Environments first.",

        "gradleCache.sort.sizeDesc": "Size ↓",
        "gradleCache.sort.sizeAsc": "Size ↑",
        "gradleCache.sort.mtimeDesc": "Newest first",
        "gradleCache.sort.mtimeAsc": "Oldest first",
        "gradleCache.title": "Gradle Global Cache",
        "gradleCache.subtitle": "Scan ~/.gradle/caches and ~/.gradle/wrapper/dists; reclaim dependencies and Wrapper distributions safely.",
        "gradleCache.section.artifacts": "Dependency Cache (modules-2)",
        "gradleCache.section.wrappers": "Wrapper Distributions",
        "gradleCache.total.artifacts": "Artifacts total",
        "gradleCache.total.wrappers": "Wrappers total",
        "gradleCache.total.combined": "Combined total",
        "gradleCache.searchPlaceholder.artifacts": "Search group:artifact or version",
        "gradleCache.searchPlaceholder.wrappers": "Search Gradle version",
        "gradleCache.column.groupArtifact": "Group : Artifact",
        "gradleCache.column.version": "Version",
        "gradleCache.column.size": "Size",
        "gradleCache.column.mtime": "Modified",
        "gradleCache.action.reveal": "Show in Finder",
        "gradleCache.action.delete": "Move to Trash",
        "gradleCache.action.deleteSelected": "Delete selected (%d)",
        "gradleCache.empty.title": "No Gradle cache found",
        "gradleCache.empty.hint": "Nothing detected under ~/.gradle. Run a Gradle build once, or visit the website to learn more.",
        "gradleCache.empty.openWebsite": "Open gradle.org",
        "gradleCache.confirmDelete.title": "Confirm move to Trash",
        "gradleCache.confirmDelete.body": "%d item(s) will be moved to Trash — you can restore them from Finder later.",
        "gradleCache.confirmDelete.confirm": "Move to Trash"
    ]

    static let zhPackagesExtra: [String: String] = [
        "rubyRepo.title": "Ruby 仓库",
        "rubyRepo.subtitle": "管理 RubyGems 镜像源、全局 Gem 与缓存",
        "rubyRepo.tab.source": "镜像源",
        "rubyRepo.tab.gems": "全局 Gem",
        "rubyRepo.tab.cache": "缓存",
        "rubyRepo.source.current": "当前源：",
        "rubyRepo.source.presets": "预设镜像",
        "rubyRepo.source.custom": "自定义 URL",
        "rubyRepo.source.apply": "应用",
        "rubyRepo.source.confirmApply": "确定要切换 RubyGems 源吗？",
        "rubyRepo.gem.uninstall": "卸载",
        "rubyRepo.gem.confirmDelete": "确定要卸载该全局 Gem 吗？",
        "rubyRepo.gem.empty": "未安装用户级 Gem",
        "rubyRepo.gem.search": "搜索 Gem 名称",
        "rubyRepo.gem.total": "共 %d 个",
        "rubyRepo.cache.confirmClean": "清理 Gem 缓存？",
        "rubyRepo.gemMissing.title": "未检测到 gem",
        "rubyRepo.gemMissing.subtitle": "PATH 上未找到 `gem` 命令。请先在开发环境中安装 Ruby。",

        "rustRepo.title": "Rust 仓库",
        "rustRepo.subtitle": "管理 Cargo 镜像、全局 Crate 与缓存",
        "rustRepo.tab.registry": "镜像源",
        "rustRepo.tab.crates": "全局 Crate",
        "rustRepo.tab.cache": "缓存",
        "rustRepo.registry.current": "当前源：",
        "rustRepo.registry.presets": "预设镜像",
        "rustRepo.registry.custom": "自定义 URL",
        "rustRepo.registry.apply": "应用",
        "rustRepo.registry.confirmApply": "确定要切换 Cargo 镜像吗？",
        "rustRepo.registry.hint": "配置写入 ~/.cargo/config.toml，替换默认 crates.io 镜像。",
        "rustRepo.crate.uninstall": "卸载",
        "rustRepo.crate.confirmDelete": "确定要卸载该 Crate 吗？",
        "rustRepo.crate.empty": "未安装用户级 Crate",
        "rustRepo.crate.search": "搜索 Crate 名称",
        "rustRepo.crate.total": "共 %d 个",
        "rustRepo.cache.confirmClean": "清理 Cargo 缓存？",
        "rustRepo.cargoMissing.title": "未检测到 cargo",
        "rustRepo.cargoMissing.subtitle": "PATH 上未找到 `cargo` 命令。请先在开发环境中安装 Rust。",

        "phpRepo.title": "PHP 仓库",
        "phpRepo.subtitle": "管理 Composer 镜像、全局包与缓存",
        "phpRepo.tab.repository": "镜像源",
        "phpRepo.tab.packages": "全局包",
        "phpRepo.tab.cache": "缓存",
        "phpRepo.repository.current": "当前源：",
        "phpRepo.repository.presets": "预设镜像",
        "phpRepo.repository.custom": "自定义 URL",
        "phpRepo.repository.apply": "应用",
        "phpRepo.repository.confirmApply": "确定要切换 Composer 镜像吗？",
        "phpRepo.pkg.uninstall": "卸载",
        "phpRepo.pkg.confirmDelete": "确定要卸载该全局包吗？",
        "phpRepo.pkg.empty": "未安装全局 Composer 包",
        "phpRepo.pkg.search": "搜索包名",
        "phpRepo.pkg.total": "共 %d 个",
        "phpRepo.cache.confirmClean": "清理 Composer 缓存？",
        "phpRepo.composerMissing.title": "未检测到 composer",
        "phpRepo.composerMissing.subtitle": "PATH 上未找到 `composer` 命令。请先安装 PHP 与 Composer。",

        "dotnetRepo.title": ".NET 仓库",
        "dotnetRepo.subtitle": "管理 NuGet 源、全局工具与缓存",
        "dotnetRepo.tab.source": "NuGet 源",
        "dotnetRepo.tab.tools": "全局工具",
        "dotnetRepo.tab.cache": "缓存",
        "dotnetRepo.source.enabled": "已启用源：",
        "dotnetRepo.source.none": "尚未配置 NuGet 源。",
        "dotnetRepo.source.presets": "预设源",
        "dotnetRepo.source.custom": "自定义源",
        "dotnetRepo.source.name": "名称",
        "dotnetRepo.source.apply": "添加/更新",
        "dotnetRepo.source.confirmApply": "确定要更新 NuGet 源吗？",
        "dotnetRepo.source.hint": "自定义源将写入用户级 NuGet.Config。",
        "dotnetRepo.tool.uninstall": "卸载",
        "dotnetRepo.tool.confirmDelete": "确定要卸载该全局工具吗？",
        "dotnetRepo.tool.empty": "未安装全局 .NET 工具",
        "dotnetRepo.tool.search": "搜索工具名称",
        "dotnetRepo.tool.total": "共 %d 个",
        "dotnetRepo.cache.confirmClean": "清理 NuGet 缓存？",
        "dotnetRepo.dotnetMissing.title": "未检测到 dotnet",
        "dotnetRepo.dotnetMissing.subtitle": "PATH 上未找到 `dotnet` 命令。请先在开发环境中安装 .NET SDK。",

        "gradleCache.sort.sizeDesc": "体积从大到小",
        "gradleCache.sort.sizeAsc": "体积从小到大",
        "gradleCache.sort.mtimeDesc": "最近修改在前",
        "gradleCache.sort.mtimeAsc": "最久未修改在前",
        "gradleCache.title": "Gradle 全局缓存",
        "gradleCache.subtitle": "扫描 ~/.gradle/caches 与 ~/.gradle/wrapper/dists，安全回收依赖与 Wrapper 发行版",
        "gradleCache.section.artifacts": "依赖缓存 (modules-2)",
        "gradleCache.section.wrappers": "Wrapper 发行版",
        "gradleCache.total.artifacts": "依赖缓存合计",
        "gradleCache.total.wrappers": "Wrapper 合计",
        "gradleCache.total.combined": "总计",
        "gradleCache.searchPlaceholder.artifacts": "搜索 group:artifact 或版本",
        "gradleCache.searchPlaceholder.wrappers": "搜索 Gradle 版本",
        "gradleCache.column.groupArtifact": "Group : Artifact",
        "gradleCache.column.version": "版本",
        "gradleCache.column.size": "体积",
        "gradleCache.column.mtime": "最近修改",
        "gradleCache.action.reveal": "在 Finder 中显示",
        "gradleCache.action.delete": "移入回收站",
        "gradleCache.action.deleteSelected": "删除选中 (%d)",
        "gradleCache.empty.title": "未发现 Gradle 缓存",
        "gradleCache.empty.hint": "尚未在 ~/.gradle 下检测到依赖或 Wrapper。请先运行一次 Gradle 构建，或访问官网了解更多。",
        "gradleCache.empty.openWebsite": "打开 Gradle 官网",
        "gradleCache.confirmDelete.title": "确认移入回收站",
        "gradleCache.confirmDelete.body": "共 %d 项将被移入回收站，可稍后从访达恢复。",
        "gradleCache.confirmDelete.confirm": "移入回收站"
    ]
}
