import Foundation

extension L10n {
    static let enHistory: [String: String] = [
        "settings.history": "History",
        "history.title": "Operation history",
        "history.subtitle": "Everything EnvMatrix changed on this Mac. Config writes with a backup can be rolled back.",
        "history.empty.title": "No operations yet",
        "history.empty.subtitle": "Mirror switches, cache cleans, runtime changes and hosts writes will show up here.",
        "history.filter.all": "All",
        "history.clear": "Clear",
        "history.rollback": "Roll back",
        "history.rolledBack": "Rolled back",
        "history.revealBackup": "Reveal backup in Finder",
        "history.rollback.confirmTitle": "Roll back \"%@\"?",
        "history.rollback.confirmMessage": "The backup\n%@\nwill be restored over\n%@\nA copy of the current file is kept first.",
        "history.rollback.entry": "Rolled back: %@",
        "history.category.runtime": "Runtimes",
        "history.category.homebrew": "Homebrew",
        "history.category.registry": "Mirrors",
        "history.category.cache": "Caches",
        "history.category.hosts": "Hosts",
        "history.category.shell": "Shell",
        "history.category.mcp": "MCP",
        "history.category.apps": "Apps",
        "history.category.other": "Other",
        "history.op.registry.npm": "Switched npm registry",
        "history.op.registry.pip": "Switched pip index",
        "history.op.registry.cargo": "Switched cargo registry",
        "history.op.registry.gem": "Switched RubyGems source",
        "history.op.registry.uv": "Switched uv index",
        "history.op.registry.pnpm": "Switched pnpm registry",
        "history.op.registry.composer": "Switched Composer repository",
        "history.op.registry.nuget": "Set NuGet primary source",
        "history.op.registry.goproxy": "Set GOPROXY",
        "history.op.registry.maven": "Updated Maven mirrors",
        "history.op.runtime.install": "Installed %@ %@",
        "history.op.runtime.activate": "Activated %@ %@",
        "history.op.runtime.uninstall": "Uninstalled %@ %@",
        "history.op.hosts.apply": "Applied hosts profile to /etc/hosts",
        "history.op.shell.save": "Saved %@",
        "history.op.mcp.add": "Added MCP server %@",
        "history.op.mcp.update": "Updated MCP server %@",
        "history.op.mcp.delete": "Deleted MCP server %@",
        "history.op.cache.npm": "Cleaned npm cache",
        "history.op.cache.pip": "Purged pip cache",
        "history.op.cache.uv": "Cleaned uv cache",
        "history.op.apps.trash": "Moved %@ to Trash"
    ]

    static let zhHistory: [String: String] = [
        "settings.history": "历史",
        "history.title": "操作历史",
        "history.subtitle": "EnvMatrix 在这台 Mac 上做过的每一次修改。带备份的配置写入可以一键回滚。",
        "history.empty.title": "还没有操作记录",
        "history.empty.subtitle": "镜像切换、缓存清理、运行时变更与 hosts 写入都会显示在这里。",
        "history.filter.all": "全部",
        "history.clear": "清空",
        "history.rollback": "回滚",
        "history.rolledBack": "已回滚",
        "history.revealBackup": "在访达中显示备份",
        "history.rollback.confirmTitle": "回滚“%@”？",
        "history.rollback.confirmMessage": "将用备份\n%@\n覆盖\n%@\n覆盖前会先保留当前文件的副本。",
        "history.rollback.entry": "已回滚：%@",
        "history.category.runtime": "运行时",
        "history.category.homebrew": "Homebrew",
        "history.category.registry": "镜像",
        "history.category.cache": "缓存",
        "history.category.hosts": "Hosts",
        "history.category.shell": "Shell",
        "history.category.mcp": "MCP",
        "history.category.apps": "应用",
        "history.category.other": "其他",
        "history.op.registry.npm": "切换 npm 镜像",
        "history.op.registry.pip": "切换 pip 镜像",
        "history.op.registry.cargo": "切换 cargo 镜像",
        "history.op.registry.gem": "切换 RubyGems 源",
        "history.op.registry.uv": "切换 uv 镜像",
        "history.op.registry.pnpm": "切换 pnpm 镜像",
        "history.op.registry.composer": "切换 Composer 镜像",
        "history.op.registry.nuget": "设置 NuGet 主源",
        "history.op.registry.goproxy": "设置 GOPROXY",
        "history.op.registry.maven": "更新 Maven 镜像",
        "history.op.runtime.install": "安装 %@ %@",
        "history.op.runtime.activate": "激活 %@ %@",
        "history.op.runtime.uninstall": "卸载 %@ %@",
        "history.op.hosts.apply": "将 hosts 方案应用到 /etc/hosts",
        "history.op.shell.save": "保存 %@",
        "history.op.mcp.add": "新增 MCP 服务器 %@",
        "history.op.mcp.update": "更新 MCP 服务器 %@",
        "history.op.mcp.delete": "删除 MCP 服务器 %@",
        "history.op.cache.npm": "清理 npm 缓存",
        "history.op.cache.pip": "清理 pip 缓存",
        "history.op.cache.uv": "清理 uv 缓存",
        "history.op.apps.trash": "将 %@ 移到废纸篓"
    ]
}
