import Foundation

extension L10n {
    static let enSystem: [String: String] = [
        "shellEnv.title": "Shell Environment",
        "shellEnv.currentShell": "current shell",
        "shellEnv.mode": "View",
        "shellEnv.mode.structured": "Structured",
        "shellEnv.mode.raw": "Raw",
        "shellEnv.export": "export",
        "shellEnv.key": "Key",
        "shellEnv.value": "Value",
        "shellEnv.quoting": "Quoting",
        "shellEnv.quoting.double": "Double",
        "shellEnv.quoting.single": "Single",
        "shellEnv.quoting.none": "None",
        "shellEnv.addVariable": "Add Variable",
        "shellEnv.addPathGroup": "Add PATH Group",
        "shellEnv.removePathGroup": "Remove Group",
        "shellEnv.addSegment": "Append",
        "shellEnv.removeSegment": "Remove",
        "shellEnv.segment.placeholder": "Enter a path segment…",
        "shellEnv.unparsedLines": "Unparsed lines",
        "shellEnv.sectionVariables": "Variables",
        "shellEnv.sectionPath": "PATH Appends",
        "shellEnv.save": "Save",
        "shellEnv.refresh": "Refresh",
        "shellEnv.emptySelect": "Select a file",
        "shellEnv.emptySelect.hint": "Pick a shell config file on the left to edit.",

        "hosts.title": "Hosts Manager",
        "hosts.mode": "View",
        "hosts.mode.structured": "Structured",
        "hosts.mode.raw": "Raw",
        "hosts.sectionEntries": "Entries",
        "hosts.addEntry": "Add Entry",
        "hosts.removeEntry": "Remove",
        "hosts.entry.enabled": "Enabled",
        "hosts.entry.ip": "IP",
        "hosts.entry.hostnames": "Hostnames (space separated)",
        "hosts.entry.comment": "Comment",
        "hosts.unparsedLines": "Unparsed lines",
        "hosts.systemPath": "System file",
        "hosts.matchesSystem": "matches /etc/hosts",
        "hosts.newProfile": "New Profile",
        "hosts.duplicate": "Duplicate",
        "hosts.rename": "Rename",
        "hosts.delete": "Delete",
        "hosts.setDefault": "Set as Default",
        "hosts.default": "default",
        "hosts.saveProfile": "Save Profile",
        "hosts.applyToSystem": "Apply to /etc/hosts",
        "hosts.applyConfirm.title": "Apply to /etc/hosts?",
        "hosts.applyConfirm.message": "This will overwrite /etc/hosts. A timestamped backup will be created in the app support directory. Administrator authentication is required.",
        "hosts.applyConfirm.ok": "Apply",
        "hosts.cancel": "Cancel",
        "hosts.ok": "OK",
        "hosts.refresh": "Refresh",
        "hosts.profileName": "Profile name",
        "hosts.emptySelect": "Select a profile",
        "hosts.emptySelect.hint": "Pick a hosts profile on the left, or create a new one.",

        "localApps.title": "Local Apps",
        "localApps.searchPlaceholder": "Search by name or bundle id",
        "localApps.empty": "No apps found",
        "localApps.refresh": "Refresh",
        "localApps.source.label": "Source",
        "localApps.source.all": "All",
        "localApps.source.brew": "Brew Cask",
        "localApps.source.appStore": "App Store",
        "localApps.source.other": "Other",
        "localApps.sort.label": "Sort",
        "localApps.sort.name": "Name",
        "localApps.sort.size": "Size",
        "localApps.sort.source": "Source",
        "localApps.column.name": "Name",
        "localApps.column.version": "Version",
        "localApps.column.bundleId": "Bundle ID",
        "localApps.column.size": "Size",
        "localApps.column.source": "Source",
        "localApps.action.open": "Open",
        "localApps.action.reveal": "Reveal in Finder",
        "localApps.action.uninstall": "Move to Trash",
        "localApps.uninstall.title": "Move to Trash?",
        "localApps.uninstall.message": "This will move the selected app to the Trash. You can restore it from the system Trash later.",
        "localApps.uninstall.confirm": "Move to Trash",
        "localApps.uninstall.cancel": "Cancel",
        "localApps.leftovers.title": "Leftover Files",
        "localApps.leftovers.message": "The following residual files reference the uninstalled bundle id. Select the ones you want to remove.",
        "localApps.leftovers.trashSelected": "Trash Selected",
        "localApps.leftovers.cancel": "Skip",
        "localApps.leftovers.empty": "No leftover files detected.",
        "localApps.leftovers.kind.preferences": "Preferences",
        "localApps.leftovers.kind.caches": "Caches",
        "localApps.leftovers.kind.appSupport": "Application Support",
        "localApps.leftovers.kind.logs": "Logs",
        "localApps.leftovers.kind.savedState": "Saved State",
        "localApps.leftovers.kind.containers": "Containers",
        "localApps.leftovers.kind.groupContainers": "Group Containers",
        "localApps.protected.tooltip": "System-managed app cannot be removed",
        "localApps.error.brewMissing": "Homebrew is not installed; brew cask source detection is disabled",
        "localApps.error.moveToTrashFailed": "Failed to move to Trash",
        "localApps.status.scanning": "Scanning applications…",

        "skills.title": "Skills",
        "skills.refresh": "Refresh",
        "skills.empty.title": "No Skills Found",
        "skills.empty.subtitle": "Configured skills directories are empty.",
        "skills.revealInFinder": "Reveal in Finder",
        "skills.delete": "Delete",
        "skills.source.unknown": "Uncategorized",

        "cli.title": "AI CLI",
        "cli.save": "Save",
        "cli.selectPrompt": "Select a CLI configuration",
        "cli.selectHint": "Choose a configuration on the left to edit its values.",
        "cli.model": "Model",
        "cli.apiBaseURL": "API Base URL",
        "cli.apiKey": "API Key",

        "mcp.title": "MCP Servers",
        "mcp.add": "Add",
        "mcp.refresh": "Refresh",
        "mcp.empty.title": "No MCP Servers",
        "mcp.empty.subtitle": "Click Add to configure a new server.",
        "mcp.edit": "Edit",
        "mcp.delete": "Delete",
        "mcp.argCount.one": "%d arg",
        "mcp.argCount.many": "%d args",
        "mcp.transport.npx": "npx",
        "mcp.transport.uvx": "uvx",
        "mcp.transport.node": "Node.js",
        "mcp.transport.python": "Python",
        "mcp.transport.other": "Other",
        "mcp.editor.editTitle": "Edit MCP Server",
        "mcp.editor.addTitle": "Add MCP Server",
        "mcp.editor.basics": "Basics",
        "mcp.editor.name": "Name",
        "mcp.editor.command": "Command",
        "mcp.editor.arguments": "Arguments",
        "mcp.editor.argsPlaceholder": "Comma-separated",
        "mcp.editor.argsHelp": "Values separated by commas, e.g. --port,8080",
        "mcp.editor.envVars": "Environment Variables",
        "mcp.editor.envKey": "KEY",
        "mcp.editor.envValue": "value",
        "mcp.editor.addVariable": "Add Variable",
        "mcp.editor.cancel": "Cancel",
        "mcp.editor.save": "Save",

        "notify.brew.success.title": "Homebrew task finished",
        "notify.brew.success.body": "brew %@ completed successfully.",
        "notify.brew.failure.title": "Homebrew task failed",
        "notify.brew.failure.body": "brew %@ did not finish. Check the operation log.",
        "notify.npm.cache.title": "npm cache cleaned",
        "notify.npm.cache.body": "The local npm cache has been fully released.",
        "notify.pip.cache.title": "pip cache purged",
        "notify.pip.cache.body": "The local pip cache has been fully released."
    ]

    static let zhSystem: [String: String] = [
        "shellEnv.title": "Shell 本地环境",
        "shellEnv.currentShell": "当前 shell",
        "shellEnv.mode": "视图",
        "shellEnv.mode.structured": "结构化",
        "shellEnv.mode.raw": "原文",
        "shellEnv.export": "export",
        "shellEnv.key": "变量名",
        "shellEnv.value": "值",
        "shellEnv.quoting": "引号",
        "shellEnv.quoting.double": "双引号",
        "shellEnv.quoting.single": "单引号",
        "shellEnv.quoting.none": "无",
        "shellEnv.addVariable": "新增变量",
        "shellEnv.addPathGroup": "新增 PATH 组",
        "shellEnv.removePathGroup": "删除本组",
        "shellEnv.addSegment": "追加",
        "shellEnv.removeSegment": "删除",
        "shellEnv.segment.placeholder": "输入路径片段…",
        "shellEnv.unparsedLines": "未解析行数",
        "shellEnv.sectionVariables": "变量",
        "shellEnv.sectionPath": "PATH 追加",
        "shellEnv.save": "保存",
        "shellEnv.refresh": "刷新",
        "shellEnv.emptySelect": "请选择一个文件",
        "shellEnv.emptySelect.hint": "从左侧选择要编辑的 shell 配置文件。",

        "hosts.title": "Hosts 管理",
        "hosts.mode": "视图",
        "hosts.mode.structured": "结构化",
        "hosts.mode.raw": "原文",
        "hosts.sectionEntries": "条目",
        "hosts.addEntry": "新增条目",
        "hosts.removeEntry": "删除",
        "hosts.entry.enabled": "启用",
        "hosts.entry.ip": "IP",
        "hosts.entry.hostnames": "主机名（空格分隔）",
        "hosts.entry.comment": "注释",
        "hosts.unparsedLines": "未解析行数",
        "hosts.systemPath": "系统文件",
        "hosts.matchesSystem": "与 /etc/hosts 一致",
        "hosts.newProfile": "新建方案",
        "hosts.duplicate": "另存为",
        "hosts.rename": "重命名",
        "hosts.delete": "删除",
        "hosts.setDefault": "设为默认",
        "hosts.default": "默认",
        "hosts.saveProfile": "保存方案",
        "hosts.applyToSystem": "应用到 /etc/hosts",
        "hosts.applyConfirm.title": "应用到 /etc/hosts？",
        "hosts.applyConfirm.message": "将覆盖 /etc/hosts，覆盖前会在应用支持目录生成带时间戳的备份，需要管理员授权。",
        "hosts.applyConfirm.ok": "应用",
        "hosts.cancel": "取消",
        "hosts.ok": "确定",
        "hosts.refresh": "刷新",
        "hosts.profileName": "方案名称",
        "hosts.emptySelect": "请选择一个方案",
        "hosts.emptySelect.hint": "从左侧选择一个 hosts 方案，或新建一个。",

        "localApps.title": "本地应用",
        "localApps.searchPlaceholder": "按名称或 Bundle ID 搜索",
        "localApps.empty": "未发现应用",
        "localApps.refresh": "刷新",
        "localApps.source.label": "来源",
        "localApps.source.all": "全部",
        "localApps.source.brew": "Brew Cask",
        "localApps.source.appStore": "App Store",
        "localApps.source.other": "其他",
        "localApps.sort.label": "排序",
        "localApps.sort.name": "名称",
        "localApps.sort.size": "大小",
        "localApps.sort.source": "来源",
        "localApps.column.name": "名称",
        "localApps.column.version": "版本",
        "localApps.column.bundleId": "Bundle ID",
        "localApps.column.size": "大小",
        "localApps.column.source": "来源",
        "localApps.action.open": "打开",
        "localApps.action.reveal": "在 Finder 中显示",
        "localApps.action.uninstall": "移到废纸篓",
        "localApps.uninstall.title": "移到废纸篓？",
        "localApps.uninstall.message": "将把该应用移动到系统废纸篓，之后可从废纸篓恢复。",
        "localApps.uninstall.confirm": "移到废纸篓",
        "localApps.uninstall.cancel": "取消",
        "localApps.leftovers.title": "残余文件",
        "localApps.leftovers.message": "以下残余文件与已卸载的 Bundle ID 相关，请勾选需要清理的项。",
        "localApps.leftovers.trashSelected": "清理所选",
        "localApps.leftovers.cancel": "跳过",
        "localApps.leftovers.empty": "未检测到残余文件",
        "localApps.leftovers.kind.preferences": "偏好设置",
        "localApps.leftovers.kind.caches": "缓存",
        "localApps.leftovers.kind.appSupport": "应用支持",
        "localApps.leftovers.kind.logs": "日志",
        "localApps.leftovers.kind.savedState": "已保存状态",
        "localApps.leftovers.kind.containers": "沙盒容器",
        "localApps.leftovers.kind.groupContainers": "组沙盒容器",
        "localApps.protected.tooltip": "系统托管应用不可移除",
        "localApps.error.brewMissing": "未安装 Homebrew，Brew Cask 来源识别已禁用",
        "localApps.error.moveToTrashFailed": "移动到废纸篓失败",
        "localApps.status.scanning": "正在扫描应用…",

        "skills.title": "技能",
        "skills.refresh": "刷新",
        "skills.empty.title": "未找到技能",
        "skills.empty.subtitle": "配置的技能目录为空。",
        "skills.revealInFinder": "在访达中显示",
        "skills.delete": "删除",
        "skills.source.unknown": "未分类",

        "cli.title": "AI 命令行",
        "cli.save": "保存",
        "cli.selectPrompt": "请选择一个 CLI 配置",
        "cli.selectHint": "在左侧选择一项配置以编辑其内容。",
        "cli.model": "模型",
        "cli.apiBaseURL": "API 基础地址",
        "cli.apiKey": "API 密钥",

        "mcp.title": "MCP 服务器",
        "mcp.add": "添加",
        "mcp.refresh": "刷新",
        "mcp.empty.title": "暂无 MCP 服务器",
        "mcp.empty.subtitle": "点击\"添加\"以配置新的服务器。",
        "mcp.edit": "编辑",
        "mcp.delete": "删除",
        "mcp.argCount.one": "%d 个参数",
        "mcp.argCount.many": "%d 个参数",
        "mcp.transport.npx": "npx",
        "mcp.transport.uvx": "uvx",
        "mcp.transport.node": "Node.js",
        "mcp.transport.python": "Python",
        "mcp.transport.other": "其他",
        "mcp.editor.editTitle": "编辑 MCP 服务器",
        "mcp.editor.addTitle": "添加 MCP 服务器",
        "mcp.editor.basics": "基本信息",
        "mcp.editor.name": "名称",
        "mcp.editor.command": "命令",
        "mcp.editor.arguments": "参数",
        "mcp.editor.argsPlaceholder": "以逗号分隔",
        "mcp.editor.argsHelp": "多个值用英文逗号分隔，例如: --port,8080",
        "mcp.editor.envVars": "环境变量",
        "mcp.editor.envKey": "键",
        "mcp.editor.envValue": "值",
        "mcp.editor.addVariable": "添加变量",
        "mcp.editor.cancel": "取消",
        "mcp.editor.save": "保存",

        "notify.brew.success.title": "Homebrew 操作完成",
        "notify.brew.success.body": "brew %@ 已成功完成。",
        "notify.brew.failure.title": "Homebrew 操作失败",
        "notify.brew.failure.body": "brew %@ 未能完成，请查看输出日志。",
        "notify.npm.cache.title": "npm 缓存已清理",
        "notify.npm.cache.body": "本地 npm 缓存已经全部释放。",
        "notify.pip.cache.title": "pip 缓存已清理",
        "notify.pip.cache.body": "本地 pip 缓存已经全部释放。"
    ]
}
