import Foundation

extension L10n {
    static let enSettings: [String: String] = [
        "settings.general": "General",
        "settings.logs": "Logs",
        "settings.about": "About",
        "settings.appearance": "Appearance",
        "settings.colorScheme": "Color Scheme",
        "settings.system": "System",
        "settings.light": "Light",
        "settings.dark": "Dark",
        "settings.language": "Language",
        "settings.languageLabel": "Interface Language",
        "settings.mirrors": "Mirror Sources",
        "settings.nodeMirror": "Node.js Mirror",
        "settings.pythonMirror": "Python Mirror",
        "settings.goMirror": "Go Mirror",
        "settings.javaMirror": "Java Mirror",
        "settings.resetDefaults": "Reset to Defaults",
        "settings.entries": "%d entries",
        "settings.clear": "Clear",
        "settings.noLogs": "No log entries.",
        "settings.version": "Version %@",
        "settings.aboutDescription": "A unified macOS control panel for managing developer runtimes and AI development environments.",
        "settings.viewGitHub": "View on GitHub",

        "settings.backups": "Backups",
        "settings.backups.title": "Configuration Backups",
        "settings.backups.subtitle": "Backups automatically created before EnvMatrix modifies your configuration files. You can restore or delete them here.",
        "settings.backups.empty": "No backups found. Backups will appear here after you apply a mirror or edit configuration through EnvMatrix.",
        "settings.backups.column.file": "Backup File",
        "settings.backups.column.target": "Target",
        "settings.backups.column.time": "Modified",
        "settings.backups.column.size": "Size",
        "settings.backups.restore": "Restore",
        "settings.backups.delete": "Delete",
        "settings.backups.reveal": "Reveal in Finder",
        "settings.backups.confirmRestore": "Restore backup? This will overwrite %@.",
        "settings.backups.confirmDelete": "Delete this backup? This cannot be undone.",
        "settings.backups.restoreSuccess": "Restored %@ from backup.",
        "settings.backups.deleteSuccess": "Backup deleted.",
        "settings.backups.kind.npmrc": "npm registry (.npmrc)",
        "settings.backups.kind.mavenSettings": "Maven settings.xml",

        "settings.diagnostics": "Diagnostics",
        "settings.diagnostics.title": "Diagnostic report",
        "settings.diagnostics.subtitle": "A Markdown snapshot of the current machine's package managers, ready to attach to issues.",
        "settings.diagnostics.generate": "Generate report",
        "settings.diagnostics.copy": "Copy",
        "settings.diagnostics.save": "Save as Markdown…",
        "settings.diagnostics.copied": "Copied to clipboard",
        "settings.diagnostics.emptyHint": "Click ‘Generate report’ to scan Homebrew / Maven / Go / npm.",

        "settings.notifications": "Notifications",
        "settings.notifications.toggle": "Notify me when long tasks finish",
        "settings.notifications.hint": "The first time this is on, macOS will ask for notification permission. Turn off and EnvMatrix will stay quiet.",

        "projenv.title": "Project Environments",
        "projenv.subtitle": "%d project roots scanned",
        "projenv.scannedIn": "Scanned in %.1fs",
        "projenv.total": "Total",
        "projenv.reclaimable": "Reclaimable",
        "projenv.searchPlaceholder": "Search project or environment path",
        "projenv.minSize": "Min size",
        "projenv.minSizeOff": "off",
        "projenv.roots": "Roots",
        "projenv.rescan": "Rescan",
        "projenv.filter.all": "All",
        "projenv.sort.menuLabel": "Sort (%@)",
        "projenv.sort.sizeDesc": "Size ↓",
        "projenv.sort.sizeAsc": "Size ↑",
        "projenv.sort.mtimeAsc": "Oldest first",
        "projenv.sort.mtimeDesc": "Newest first",
        "projenv.health.active": "Active",
        "projenv.health.idle": "Idle",
        "projenv.health.abandoned": "Abandoned",
        "projenv.overview.total": "Total",
        "projenv.overview.reclaimable": "Reclaimable",
        "projenv.overview.abandonedCount": "Abandoned count",
        "projenv.overview.abandonedSize": "Abandoned size",
        "projenv.overview.cleanAbandoned": "Clean all abandoned",
        "projenv.toolbar.deleteSelected": "Delete selected (%d)",
        "projenv.multi.title": "%1$d selected · %2$@",
        "projenv.multi.subtitle": "Path preview",
        "projenv.multi.moreItems": "and %d more…",
        "projenv.multi.deleteSelected": "Delete selected",
        "projenv.batchDelete.title": "Confirm batch delete",
        "projenv.batchDelete.body": "%1$d items will be moved to Trash · %2$@ total.",
        "projenv.batchDelete.confirm": "Move to Trash",
        "projenv.batchDelete.morePaths": "and %d more paths…",
        "projenv.abandonedCleanup.title": "Clean abandoned items",
        "projenv.abandonedCleanup.body": "%1$d abandoned items will be moved to Trash · %2$@ total.",
        "projenv.abandonedCleanup.confirm": "Clean all",
        "projenv.abandonedCleanup.morePaths": "and %d more paths…",
        "projenv.rootsEditor.includeXcode": "Scan Xcode DerivedData",
        "projenv.kind.rustTarget": "Rust target",
        "projenv.kind.xcodeDerivedData": "Xcode DerivedData",
        "projenv.kind.gradleCache": "Gradle cache",
        "projenv.kind.mavenTarget": "Maven target",
        "projenv.action.reveal": "Reveal in Finder",
        "projenv.action.revealProject": "Reveal Project",
        "projenv.action.openTerminal": "Open in Terminal",
        "projenv.action.reinstall": "Reinstall",
        "projenv.action.delete": "Move to Trash",
        "projenv.actions": "Actions",
        "projenv.trashHint": "Deletions move the target folder to the Trash. You can restore it from there if needed.",
        "projenv.detail.pickHint": "Select a project environment to see details.",
        "projenv.field.projectRoot": "Project Root",
        "projenv.field.envPath": "Environment Path",
        "projenv.field.size": "Size",
        "projenv.field.pythonVersion": "Python Version",
        "projenv.field.packageManager": "Package Manager",
        "projenv.field.modified": "Modified",
        "projenv.pm.unknown": "Unknown",
        "projenv.deleteConfirm.title": "Move to Trash?",
        "projenv.deleteConfirm.body": "This will move the following folder to the Trash:\n\n%@\n\nSize: %@\n\nYou can restore it from Trash if needed.",
        "projenv.deleteConfirm.confirm": "Move to Trash",
        "projenv.cancel": "Cancel",
        "projenv.done": "Done",
        "projenv.rootsEditor.title": "Project Roots",
        "projenv.rootsEditor.hint": "Add folders where your projects live. EnvMatrix scans them recursively (bounded depth) to find venv and node_modules.",
        "projenv.rootsEditor.add": "Add Root",
        "projenv.log.title": "Operation Log",
        "projenv.scanning": "Scanning project roots…",
        "projenv.empty.noRoots": "No project roots configured. Add one to start scanning.",
        "projenv.empty.noEnvs": "No project environments found in configured roots."
    ]

    static let zhSettings: [String: String] = [
        "settings.general": "通用",
        "settings.logs": "日志",
        "settings.about": "关于",
        "settings.appearance": "外观",
        "settings.colorScheme": "配色方案",
        "settings.system": "跟随系统",
        "settings.light": "浅色",
        "settings.dark": "深色",
        "settings.language": "语言",
        "settings.languageLabel": "界面语言",
        "settings.mirrors": "镜像源",
        "settings.nodeMirror": "Node.js 镜像",
        "settings.pythonMirror": "Python 镜像",
        "settings.goMirror": "Go 镜像",
        "settings.javaMirror": "Java 镜像",
        "settings.resetDefaults": "恢复默认",
        "settings.entries": "共 %d 条",
        "settings.clear": "清除",
        "settings.noLogs": "暂无日志。",
        "settings.version": "版本 %@",
        "settings.aboutDescription": "一款统一的 macOS 控制面板，用于管理开发者运行时和 AI 开发环境。",
        "settings.viewGitHub": "在 GitHub 上查看",

        "settings.backups": "备份",
        "settings.backups.title": "配置文件备份",
        "settings.backups.subtitle": "EnvMatrix 修改配置文件前会自动生成的备份。你可以在这里一键还原或删除。",
        "settings.backups.empty": "暂无备份。通过 EnvMatrix 切换镜像或修改配置后，备份会自动出现在这里。",
        "settings.backups.column.file": "备份文件",
        "settings.backups.column.target": "目标",
        "settings.backups.column.time": "修改时间",
        "settings.backups.column.size": "大小",
        "settings.backups.restore": "还原",
        "settings.backups.delete": "删除",
        "settings.backups.reveal": "在 Finder 中显示",
        "settings.backups.confirmRestore": "还原此备份？这将覆盖 %@。",
        "settings.backups.confirmDelete": "确认删除该备份？此操作不可撤销。",
        "settings.backups.restoreSuccess": "已从备份还原 %@。",
        "settings.backups.deleteSuccess": "备份已删除。",
        "settings.backups.kind.npmrc": "npm 镜像 (.npmrc)",
        "settings.backups.kind.mavenSettings": "Maven settings.xml",

        "settings.diagnostics": "诊断",
        "settings.diagnostics.title": "诊断报告",
        "settings.diagnostics.subtitle": "汇总当前机器的包管理状态，方便附加到 Issue。",
        "settings.diagnostics.generate": "生成报告",
        "settings.diagnostics.copy": "复制",
        "settings.diagnostics.save": "保存为 Markdown…",
        "settings.diagnostics.copied": "已复制到剪贴板",
        "settings.diagnostics.emptyHint": "点击「生成报告」以扫描 Homebrew / Maven / Go / npm 状态。",

        "settings.notifications": "通知",
        "settings.notifications.toggle": "长任务完成时发送系统通知",
        "settings.notifications.hint": "首次开启会请求 macOS 的通知权限；关闭后 EnvMatrix 不会再打扰你。",

        "projenv.title": "项目环境",
        "projenv.subtitle": "已扫描 %d 个项目根目录",
        "projenv.scannedIn": "耗时 %.1f 秒",
        "projenv.total": "总计",
        "projenv.reclaimable": "可回收空间",
        "projenv.searchPlaceholder": "搜索项目或环境路径",
        "projenv.minSize": "最小体积",
        "projenv.minSizeOff": "不限",
        "projenv.roots": "根目录",
        "projenv.rescan": "重新扫描",
        "projenv.filter.all": "全部",
        "projenv.sort.menuLabel": "排序 (%@)",
        "projenv.sort.sizeDesc": "体积从大到小",
        "projenv.sort.sizeAsc": "体积从小到大",
        "projenv.sort.mtimeAsc": "最久未修改在前",
        "projenv.sort.mtimeDesc": "最近修改在前",
        "projenv.health.active": "活跃",
        "projenv.health.idle": "闲置",
        "projenv.health.abandoned": "疑似废弃",
        "projenv.overview.total": "总数",
        "projenv.overview.reclaimable": "可回收空间",
        "projenv.overview.abandonedCount": "废弃项数量",
        "projenv.overview.abandonedSize": "废弃项体积",
        "projenv.overview.cleanAbandoned": "清理所有废弃项",
        "projenv.toolbar.deleteSelected": "删除选中 (%d)",
        "projenv.multi.title": "已选 %1$d 项 · %2$@",
        "projenv.multi.subtitle": "路径预览",
        "projenv.multi.moreItems": "还有 %d 项…",
        "projenv.multi.deleteSelected": "删除选中",
        "projenv.batchDelete.title": "确认批量删除",
        "projenv.batchDelete.body": "将把 %1$d 个项目移入回收站，共 %2$@。",
        "projenv.batchDelete.confirm": "移入回收站",
        "projenv.batchDelete.morePaths": "还有 %d 条路径…",
        "projenv.abandonedCleanup.title": "清理所有废弃项",
        "projenv.abandonedCleanup.body": "将把 %1$d 个废弃项目移入回收站，共 %2$@。",
        "projenv.abandonedCleanup.confirm": "全部清理",
        "projenv.abandonedCleanup.morePaths": "还有 %d 条路径…",
        "projenv.rootsEditor.includeXcode": "扫描 Xcode DerivedData",
        "projenv.kind.rustTarget": "Rust target",
        "projenv.kind.xcodeDerivedData": "Xcode DerivedData",
        "projenv.kind.gradleCache": "Gradle 缓存",
        "projenv.kind.mavenTarget": "Maven target",
        "projenv.action.reveal": "在访达中显示",
        "projenv.action.revealProject": "定位项目",
        "projenv.action.openTerminal": "在终端中打开",
        "projenv.action.reinstall": "重新安装",
        "projenv.action.delete": "移到废纸篓",
        "projenv.actions": "操作",
        "projenv.trashHint": "删除会将目标文件夹移动到废纸篓，如有需要可从废纸篓恢复。",
        "projenv.detail.pickHint": "在左侧选择一个项目环境以查看详情。",
        "projenv.field.projectRoot": "项目根目录",
        "projenv.field.envPath": "环境路径",
        "projenv.field.size": "大小",
        "projenv.field.pythonVersion": "Python 版本",
        "projenv.field.packageManager": "包管理器",
        "projenv.field.modified": "修改时间",
        "projenv.pm.unknown": "未知",
        "projenv.deleteConfirm.title": "移到废纸篓？",
        "projenv.deleteConfirm.body": "将会把以下文件夹移动到废纸篓：\n\n%@\n\n大小：%@\n\n如有需要可从废纸篓恢复。",
        "projenv.deleteConfirm.confirm": "移到废纸篓",
        "projenv.cancel": "取消",
        "projenv.done": "完成",
        "projenv.rootsEditor.title": "项目根目录",
        "projenv.rootsEditor.hint": "添加你存放项目的目录，EnvMatrix 将递归扫描（有深度限制）以查找 venv 与 node_modules。",
        "projenv.rootsEditor.add": "添加根目录",
        "projenv.log.title": "操作日志",
        "projenv.scanning": "正在扫描项目根目录…",
        "projenv.empty.noRoots": "尚未配置项目根目录，添加一个以开始扫描。",
        "projenv.empty.noEnvs": "配置的根目录下未发现任何项目环境。"
    ]
}
