import Foundation

extension L10n {
    static let enRuntime: [String: String] = [
        "runtime.installed": "Installed",
        "runtime.available": "Available",
        "runtime.active": "Active",
        "runtime.none": "None",
        "runtime.systemDefault": "System Default",
        "runtime.refresh": "Refresh",
        "runtime.loading": "Loading versions...",
        "runtime.noAvailable": "No available versions.",
        "runtime.noInstalled": "No installed versions. Switch to Available to install one.",
        "runtime.install": "Install",
        "runtime.installedLabel": "Installed",
        "runtime.setActive": "Set Active",
        "runtime.uninstall": "Uninstall",
        "runtime.uninstallTitle": "Uninstall %@?",
        "runtime.cancel": "Cancel",
        "runtime.revealInFinder": "Reveal in Finder",
        "runtime.uninstallSystemMessage": "EnvMatrix will remove the folder:\n%@\n\nIf it was installed via brew / sdkman / nvm / pkg, using its own uninstaller is safer. Paths owned by the OS may require sudo and will be rejected.",
        "runtime.uninstallMessage": "This will remove %@ %@ from your system.",
        "runtime.uninstallSystemTooltip": "Uninstall this system runtime (will confirm before deleting)",
        "runtime.uninstallTooltip": "Uninstall this version",
        "runtime.systemBadge": "System",
        "runtime.usage": "Usage",
        "runtime.usage.total": "Total on disk",
        "runtime.usage.loading": "Calculating disk usage…",
        "runtime.usage.empty": "No installed versions to measure.",
        "runtime.usage.unknown": "Unknown",
        "runtime.usage.managed": "Managed",
        "runtime.usage.system": "System",
        "runtime.usage.recompute": "Recompute",
        "runtime.group.managed": "Managed",
        "runtime.group.system": "System",
        "runtime.group.count": "%d"
    ]

    static let zhRuntime: [String: String] = [
        "runtime.installed": "已安装",
        "runtime.available": "可用版本",
        "runtime.active": "当前",
        "runtime.none": "无",
        "runtime.systemDefault": "系统默认",
        "runtime.refresh": "刷新",
        "runtime.loading": "正在加载版本...",
        "runtime.noAvailable": "没有可用版本。",
        "runtime.noInstalled": "尚未安装任何版本。切换到\"可用版本\"进行安装。",
        "runtime.install": "安装",
        "runtime.installedLabel": "已安装",
        "runtime.setActive": "设为活动",
        "runtime.uninstall": "卸载",
        "runtime.uninstallTitle": "卸载 %@?",
        "runtime.cancel": "取消",
        "runtime.revealInFinder": "在访达中显示",
        "runtime.uninstallSystemMessage": "EnvMatrix 将删除以下文件夹:\n%@\n\n如果它是通过 brew / sdkman / nvm / pkg 安装的，使用其自带的卸载工具会更安全。系统所属的路径可能需要 sudo 权限，将被拒绝。",
        "runtime.uninstallMessage": "此操作将从系统中移除 %@ %@。",
        "runtime.uninstallSystemTooltip": "卸载此系统运行时（删除前会二次确认）",
        "runtime.uninstallTooltip": "卸载此版本",
        "runtime.systemBadge": "系统",
        "runtime.usage": "用量",
        "runtime.usage.total": "总占用",
        "runtime.usage.loading": "正在计算磁盘占用…",
        "runtime.usage.empty": "尚未安装任何版本，无法统计占用。",
        "runtime.usage.unknown": "未知",
        "runtime.usage.managed": "托管",
        "runtime.usage.system": "系统",
        "runtime.usage.recompute": "重新计算",
        "runtime.group.managed": "托管版本",
        "runtime.group.system": "系统版本",
        "runtime.group.count": "%d"
    ]
}
