import Foundation

extension L10n {
    static let enPackages: [String: String] = [
        "brew.title": "Homebrew",
        "brew.notInstalled.title": "Homebrew Not Found",
        "brew.notInstalled.subtitle": "EnvMatrix couldn't find a `brew` executable at /opt/homebrew/bin/brew or /usr/local/bin/brew. Install Homebrew to manage packages here.",
        "brew.formulae": "Formulae",
        "brew.casks": "Casks",
        "brew.refresh": "Refresh",
        "brew.loading": "Loading Homebrew inventory…",
        "brew.emptyList": "No packages match the current filters.",
        "brew.searchPlaceholder": "Search name or description",
        "brew.outdatedCount": "%d outdated",
        "brew.upgradeAll": "Upgrade All",
        "brew.cleanup": "Cleanup",
        "brew.update": "brew update",
        "brew.filter.outdatedOnly": "Outdated only",
        "brew.filter.requestedOnly": "Requested only",
        "brew.action.upgrade": "Upgrade",
        "brew.action.uninstall": "Uninstall",
        "brew.action.pin": "Pin",
        "brew.action.unpin": "Unpin",
        "brew.action.openHomepage": "Open Homepage",
        "brew.detail.selectHint": "Select a package to see details.",
        "brew.detail.kind": "Kind",
        "brew.detail.installedVersion": "Installed",
        "brew.detail.latestVersion": "Latest",
        "brew.detail.homepage": "Homepage",
        "brew.detail.autoUpdates": "Auto Updates",
        "brew.detail.installedAt": "Installed At",
        "brew.detail.deprecationReason": "Deprecation",
        "brew.detail.dependencies": "Dependencies",
        "brew.yes": "Yes",
        "brew.no": "No",

        "mavenRepo.title": "Java Global",
        "mavenRepo.subtitle": "Scan Maven local repository ~/.m2/repository; manage settings.xml mirrors and artifacts",
        "mavenRepo.refresh": "Refresh",
        "mavenRepo.addPreset": "Add Preset",
        "mavenRepo.settingsFile": "settings.xml:",
        "mavenRepo.localRepository": "localRepository:",
        "mavenRepo.active": "Active",
        "mavenRepo.mirrorOfFormat": "mirrorOf: %@",
        "mavenRepo.empty.title": "No Mirrors Configured",
        "mavenRepo.empty.subtitle": "Use the + button to add a preset mirror (Aliyun, Tencent, HuaweiCloud, Netease).",
        "mavenRepo.tab.mirrors": "Mirrors",
        "mavenRepo.tab.localArtifacts": "Local Artifacts",
        "mavenRepo.tab.gradleCache": "Gradle Cache",
        "mavenRepo.artifact.searchPlaceholder": "Search groupId, artifactId or version",
        "mavenRepo.artifact.countFormat": "%d artifacts",
        "mavenRepo.artifact.totalSizeFormat": "Total: %@",
        "mavenRepo.artifact.versionCountFormat": "%d versions",
        "mavenRepo.artifact.sortByName": "Sort by Name",
        "mavenRepo.artifact.sortBySize": "Sort by Size",
        "mavenRepo.artifact.sortByModified": "Sort by Modified",
        "mavenRepo.artifact.ascending": "Ascending",
        "mavenRepo.artifact.loading": "Scanning local repository…",
        "mavenRepo.artifact.notFound.title": "Local Repository Not Found",
        "mavenRepo.artifact.notFound.subtitle": "No directory at %@\n\nRun a Maven build first to populate ~/.m2/repository.",
        "mavenRepo.artifact.empty.title": "No Artifacts",
        "mavenRepo.artifact.empty.subtitle": "No downloaded artifacts match your search.",
        "mavenRepo.artifact.deleteAll": "Delete all versions",
        "mavenRepo.artifact.confirmDelete": "Delete %@?",
        "mavenRepo.artifact.confirmDeleteVersion": "Delete %@ (%@)?",
        "mavenRepo.artifact.confirmDeleteMessage": "This will remove %@ from disk. This action cannot be undone.",

        "goRepo.title": "Go Repository",
        "goRepo.subtitle": "Manage GOPROXY mirror and clean local GOMODCACHE",
        "goRepo.tab.proxy": "GOPROXY",
        "goRepo.tab.localCache": "Local Modules",
        "goRepo.proxy.current": "Current GOPROXY:",
        "goRepo.proxy.applyPreset": "Apply Preset",
        "goRepo.proxy.customPlaceholder": "Custom GOPROXY (comma-separated)",
        "goRepo.proxy.save": "Save",
        "goRepo.proxy.saved": "GOPROXY updated",
        "goRepo.cache.searchPlaceholder": "Search module or version",
        "goRepo.cache.countFormat": "%d modules",
        "goRepo.cache.totalSizeFormat": "Total: %@",
        "goRepo.cache.versionCountFormat": "%d versions",
        "goRepo.cache.sortByName": "Sort by Name",
        "goRepo.cache.sortBySize": "Sort by Size",
        "goRepo.cache.sortByModified": "Sort by Modified",
        "goRepo.cache.ascending": "Ascending",
        "goRepo.cache.loading": "Scanning GOMODCACHE…",
        "goRepo.cache.notFound.title": "GOMODCACHE Not Found",
        "goRepo.cache.notFound.subtitle": "No directory at %@\n\nRun a Go build first to populate the module cache.",
        "goRepo.cache.empty.title": "No Modules",
        "goRepo.cache.empty.subtitle": "No downloaded modules match your search.",
        "goRepo.cache.deleteAll": "Delete all versions",
        "goRepo.cache.confirmDelete": "Delete %@?",
        "goRepo.cache.confirmDeleteVersion": "Delete %@ (%@)?",
        "goRepo.cache.confirmDeleteMessage": "This will remove %@ from disk. This action cannot be undone.",
        "goRepo.goMissing.title": "Go Not Found",
        "goRepo.goMissing.subtitle": "The `go` command is not on PATH. Install Go from EnvMatrix Dev Environments first.",

        "nodeRepo.title": "Node Repository",
        "nodeRepo.subtitle": "Manage npm registry, global packages and cache",
        "nodeRepo.tab.registry": "Registry",
        "nodeRepo.tab.global": "Global Packages",
        "nodeRepo.tab.cache": "Cache",
        "nodeRepo.registry.current": "Current registry:",
        "nodeRepo.registry.applyPreset": "Apply Preset",
        "nodeRepo.registry.customPlaceholder": "Custom registry URL",
        "nodeRepo.registry.save": "Save",
        "nodeRepo.registry.saved": "Registry updated",
        "nodeRepo.registry.confirmTitle": "Update npm registry?",
        "nodeRepo.registry.confirmMessage": "The value in ~/.npmrc will change to %@. A backup will be written to ~/.npmrc.envmatrix.bak.",
        "nodeRepo.global.searchPlaceholder": "Search package name",
        "nodeRepo.global.countFormat": "%d packages",
        "nodeRepo.global.loading": "Loading global packages…",
        "nodeRepo.global.empty.title": "No Global Packages",
        "nodeRepo.global.empty.subtitle": "There are no user-installed global npm packages.",
        "nodeRepo.global.uninstall": "Uninstall",
        "nodeRepo.global.confirmUninstall": "Uninstall %@?",
        "nodeRepo.global.confirmUninstallMessage": "This will run `npm uninstall -g %@`.",
        "nodeRepo.cache.location": "Cache location:",
        "nodeRepo.cache.sizeFormat": "Size: %@",
        "nodeRepo.cache.clean": "Clean Cache",
        "nodeRepo.cache.confirmClean": "Clean npm cache?",
        "nodeRepo.cache.confirmCleanMessage": "This will run `npm cache clean --force`. Downloaded tarballs will need to be re-fetched.",
        "nodeRepo.cache.cleaned": "Cache cleaned",
        "nodeRepo.npmMissing.title": "npm Not Found",
        "nodeRepo.npmMissing.subtitle": "The `npm` command is not on PATH. Install Node.js from EnvMatrix Dev Environments first.",
        "nodeRepo.tab.globalPkg": "Global Packages",
        "nodeRepo.registry.presets": "Preset mirrors",
        "nodeRepo.registry.custom": "Custom URL",
        "nodeRepo.registry.apply": "Apply",
        "nodeRepo.registry.confirmApply": "Switch npm registry?",
        "nodeRepo.msg.saved": "Saved",
        "nodeRepo.msg.invalidURL": "URL must start with http:// or https://",
        "nodeRepo.pkg.uninstall": "Uninstall",
        "nodeRepo.pkg.confirmDelete": "Uninstall this global package?",
        "nodeRepo.pkg.empty": "No global packages installed",
        "nodeRepo.pkg.search": "Search packages",
        "nodeRepo.pkg.total": "%d total",
        "nodeRepo.cache.path": "Cache directory",
        "nodeRepo.cache.size": "Cache size",

        "pythonRepo.title": "Python Repository",
        "pythonRepo.subtitle": "Manage pip index-url, user packages and wheel cache",
        "pythonRepo.tab.index": "Index",
        "pythonRepo.tab.globalPkg": "User Packages",
        "pythonRepo.tab.cache": "Cache",
        "pythonRepo.index.current": "Current index:",
        "pythonRepo.index.presets": "Preset mirrors",
        "pythonRepo.index.custom": "Custom URL",
        "pythonRepo.index.apply": "Apply",
        "pythonRepo.index.confirmApply": "Switch pip index?",
        "pythonRepo.msg.saved": "Saved",
        "pythonRepo.msg.invalidURL": "URL must start with http:// or https://",
        "pythonRepo.pkg.uninstall": "Uninstall",
        "pythonRepo.pkg.confirmDelete": "Uninstall this Python package?",
        "pythonRepo.pkg.empty": "No user-installed Python packages",
        "pythonRepo.pkg.search": "Search packages",
        "pythonRepo.pkg.total": "%d total",
        "pythonRepo.cache.path": "Cache directory",
        "pythonRepo.cache.size": "Cache size",
        "pythonRepo.cache.clean": "Purge cache",
        "pythonRepo.cache.confirmClean": "Purge pip cache?",
        "pythonRepo.cache.cleaned": "Cache purged",
        "pythonRepo.pipMissing.title": "pip Not Found",
        "pythonRepo.pipMissing.subtitle": "The `pip3` command is not on PATH. Install Python from EnvMatrix Dev Environments first."
    ]

    static let zhPackages: [String: String] = [
        "brew.title": "Homebrew",
        "brew.notInstalled.title": "未找到 Homebrew",
        "brew.notInstalled.subtitle": "EnvMatrix 在 /opt/homebrew/bin/brew 或 /usr/local/bin/brew 未找到 brew 可执行文件。请先安装 Homebrew。",
        "brew.formulae": "Formula",
        "brew.casks": "Cask",
        "brew.refresh": "刷新",
        "brew.loading": "正在加载 Homebrew 清单…",
        "brew.emptyList": "当前筛选条件下没有匹配的包。",
        "brew.searchPlaceholder": "搜索名称或描述",
        "brew.outdatedCount": "%d 个可升级",
        "brew.upgradeAll": "全部升级",
        "brew.cleanup": "清理缓存",
        "brew.update": "更新元数据",
        "brew.filter.outdatedOnly": "仅显示可升级",
        "brew.filter.requestedOnly": "仅显示手动安装",
        "brew.action.upgrade": "升级",
        "brew.action.uninstall": "卸载",
        "brew.action.pin": "锁定版本",
        "brew.action.unpin": "解锁版本",
        "brew.action.openHomepage": "打开主页",
        "brew.detail.selectHint": "在左侧选择一个包以查看详情。",
        "brew.detail.kind": "类型",
        "brew.detail.installedVersion": "已安装",
        "brew.detail.latestVersion": "最新版本",
        "brew.detail.homepage": "主页",
        "brew.detail.autoUpdates": "自动更新",
        "brew.detail.installedAt": "安装时间",
        "brew.detail.deprecationReason": "废弃原因",
        "brew.detail.dependencies": "依赖",
        "brew.yes": "是",
        "brew.no": "否",

        "mavenRepo.title": "Java 全局环境",
        "mavenRepo.subtitle": "扫描 Maven 本地仓库 ~/.m2/repository，管理 settings.xml 镜像与依赖",
        "mavenRepo.refresh": "刷新",
        "mavenRepo.addPreset": "添加预设",
        "mavenRepo.settingsFile": "settings.xml：",
        "mavenRepo.localRepository": "本地仓库：",
        "mavenRepo.active": "已启用",
        "mavenRepo.mirrorOfFormat": "mirrorOf：%@",
        "mavenRepo.empty.title": "尚未配置镜像",
        "mavenRepo.empty.subtitle": "点击右上角 + 号添加预设镜像（阿里云 / 腾讯云 / 华为云 / 网易）。",
        "mavenRepo.tab.mirrors": "镜像源",
        "mavenRepo.tab.localArtifacts": "本地依赖",
        "mavenRepo.tab.gradleCache": "Gradle 缓存",
        "mavenRepo.artifact.searchPlaceholder": "搜索 groupId、artifactId 或 version",
        "mavenRepo.artifact.countFormat": "共 %d 个依赖",
        "mavenRepo.artifact.totalSizeFormat": "总计：%@",
        "mavenRepo.artifact.versionCountFormat": "%d 个版本",
        "mavenRepo.artifact.sortByName": "按名称排序",
        "mavenRepo.artifact.sortBySize": "按大小排序",
        "mavenRepo.artifact.sortByModified": "按修改时间排序",
        "mavenRepo.artifact.ascending": "升序",
        "mavenRepo.artifact.loading": "正在扫描本地仓库…",
        "mavenRepo.artifact.notFound.title": "未找到本地仓库",
        "mavenRepo.artifact.notFound.subtitle": "路径 %@ 不存在。\n\n请先运行一次 Maven 构建以生成 ~/.m2/repository。",
        "mavenRepo.artifact.empty.title": "暂无依赖",
        "mavenRepo.artifact.empty.subtitle": "当前搜索条件下没有下载的依赖。",
        "mavenRepo.artifact.deleteAll": "删除所有版本",
        "mavenRepo.artifact.confirmDelete": "删除 %@？",
        "mavenRepo.artifact.confirmDeleteVersion": "删除 %@（%@）？",
        "mavenRepo.artifact.confirmDeleteMessage": "此操作将从磁盘移除 %@，无法撤销。",

        "goRepo.title": "Go 仓库",
        "goRepo.subtitle": "管理 GOPROXY 镜像并清理本地 GOMODCACHE",
        "goRepo.tab.proxy": "GOPROXY",
        "goRepo.tab.localCache": "本地模块",
        "goRepo.proxy.current": "当前 GOPROXY：",
        "goRepo.proxy.applyPreset": "应用预设",
        "goRepo.proxy.customPlaceholder": "自定义 GOPROXY（英文逗号分隔）",
        "goRepo.proxy.save": "保存",
        "goRepo.proxy.saved": "GOPROXY 已更新",
        "goRepo.cache.searchPlaceholder": "搜索模块或版本",
        "goRepo.cache.countFormat": "共 %d 个模块",
        "goRepo.cache.totalSizeFormat": "总计：%@",
        "goRepo.cache.versionCountFormat": "%d 个版本",
        "goRepo.cache.sortByName": "按名称排序",
        "goRepo.cache.sortBySize": "按大小排序",
        "goRepo.cache.sortByModified": "按修改时间排序",
        "goRepo.cache.ascending": "升序",
        "goRepo.cache.loading": "正在扫描 GOMODCACHE…",
        "goRepo.cache.notFound.title": "未找到 GOMODCACHE",
        "goRepo.cache.notFound.subtitle": "路径 %@ 不存在。\n\n请先执行一次 Go 构建以生成模块缓存。",
        "goRepo.cache.empty.title": "暂无模块",
        "goRepo.cache.empty.subtitle": "当前搜索条件下没有下载的模块。",
        "goRepo.cache.deleteAll": "删除所有版本",
        "goRepo.cache.confirmDelete": "删除 %@？",
        "goRepo.cache.confirmDeleteVersion": "删除 %@（%@）？",
        "goRepo.cache.confirmDeleteMessage": "此操作将从磁盘移除 %@，无法撤销。",
        "goRepo.goMissing.title": "未检测到 Go",
        "goRepo.goMissing.subtitle": "PATH 上未找到 `go` 命令。请先在开发环境中安装 Go。",

        "nodeRepo.title": "Node 仓库",
        "nodeRepo.subtitle": "管理 npm 镜像、全局包与缓存",
        "nodeRepo.tab.registry": "镜像",
        "nodeRepo.tab.global": "全局包",
        "nodeRepo.tab.cache": "缓存",
        "nodeRepo.registry.current": "当前镜像：",
        "nodeRepo.registry.applyPreset": "应用预设",
        "nodeRepo.registry.customPlaceholder": "自定义镜像 URL",
        "nodeRepo.registry.save": "保存",
        "nodeRepo.registry.saved": "镜像已更新",
        "nodeRepo.registry.confirmTitle": "更新 npm 镜像？",
        "nodeRepo.registry.confirmMessage": "~/.npmrc 中的 registry 将改为 %@，并生成备份 ~/.npmrc.envmatrix.bak。",
        "nodeRepo.global.searchPlaceholder": "搜索包名",
        "nodeRepo.global.countFormat": "共 %d 个包",
        "nodeRepo.global.loading": "正在加载全局包…",
        "nodeRepo.global.empty.title": "暂无全局包",
        "nodeRepo.global.empty.subtitle": "当前没有用户全局安装的 npm 包。",
        "nodeRepo.global.uninstall": "卸载",
        "nodeRepo.global.confirmUninstall": "卸载 %@？",
        "nodeRepo.global.confirmUninstallMessage": "将执行 `npm uninstall -g %@`。",
        "nodeRepo.cache.location": "缓存路径：",
        "nodeRepo.cache.sizeFormat": "大小：%@",
        "nodeRepo.cache.clean": "清理缓存",
        "nodeRepo.cache.confirmClean": "清理 npm 缓存？",
        "nodeRepo.cache.confirmCleanMessage": "将执行 `npm cache clean --force`。已下载的 tarball 需重新拉取。",
        "nodeRepo.cache.cleaned": "缓存已清理",
        "nodeRepo.npmMissing.title": "未检测到 npm",
        "nodeRepo.npmMissing.subtitle": "PATH 上未找到 `npm` 命令。请先在开发环境中安装 Node.js。",
        "nodeRepo.tab.globalPkg": "全局包",
        "nodeRepo.registry.presets": "预设镜像",
        "nodeRepo.registry.custom": "自定义 URL",
        "nodeRepo.registry.apply": "应用",
        "nodeRepo.registry.confirmApply": "确定要切换 npm registry 吗？",
        "nodeRepo.msg.saved": "已保存",
        "nodeRepo.msg.invalidURL": "URL 必须以 http:// 或 https:// 开头",
        "nodeRepo.pkg.uninstall": "卸载",
        "nodeRepo.pkg.confirmDelete": "确定要卸载该全局包吗？",
        "nodeRepo.pkg.empty": "未安装全局包",
        "nodeRepo.pkg.search": "搜索包名",
        "nodeRepo.pkg.total": "共 %d 个",
        "nodeRepo.cache.path": "缓存目录",
        "nodeRepo.cache.size": "缓存大小",

        "pythonRepo.title": "Python 仓库",
        "pythonRepo.subtitle": "管理 pip index-url、用户级包与 wheel 缓存",
        "pythonRepo.tab.index": "镜像源",
        "pythonRepo.tab.globalPkg": "用户包",
        "pythonRepo.tab.cache": "缓存",
        "pythonRepo.index.current": "当前 index：",
        "pythonRepo.index.presets": "预设镜像",
        "pythonRepo.index.custom": "自定义 URL",
        "pythonRepo.index.apply": "应用",
        "pythonRepo.index.confirmApply": "确定要切换 pip 镜像吗？",
        "pythonRepo.msg.saved": "已保存",
        "pythonRepo.msg.invalidURL": "URL 必须以 http:// 或 https:// 开头",
        "pythonRepo.pkg.uninstall": "卸载",
        "pythonRepo.pkg.confirmDelete": "确定要卸载该 Python 包吗？",
        "pythonRepo.pkg.empty": "未安装用户级 Python 包",
        "pythonRepo.pkg.search": "搜索包名",
        "pythonRepo.pkg.total": "共 %d 个",
        "pythonRepo.cache.path": "缓存目录",
        "pythonRepo.cache.size": "缓存大小",
        "pythonRepo.cache.clean": "清理缓存",
        "pythonRepo.cache.confirmClean": "清理 pip 缓存？",
        "pythonRepo.cache.cleaned": "缓存已清理",
        "pythonRepo.pipMissing.title": "未检测到 pip",
        "pythonRepo.pipMissing.subtitle": "PATH 上未找到 `pip3` 命令。请先在开发环境中安装 Python。"
    ]
}
