import Foundation

extension L10n {
    static let en: [String: String] = [
        "app.name": "EnvMatrix",
        "app.welcome.title": "Welcome to EnvMatrix",
        "app.welcome.subtitle": "Select an item from the sidebar to get started.",
        "app.underConstruction": "This section is under construction.",

        "nav.overview": "Overview",
        "nav.devEnvironments": "Dev Environments",
        "nav.packages": "Packages",
        "nav.aiEnvironments": "AI Environments",
        "nav.system": "System",
        "nav.dashboard": "Dashboard",
        "nav.homebrew": "Homebrew",
        "nav.mavenRepo": "Maven Repository",
        "nav.skills": "Skills",
        "nav.aiCLI": "AI CLI",
        "nav.mcpServers": "MCP Servers",
        "nav.settings": "Settings",

        "dashboard.title": "Dashboard",
        "dashboard.subtitle": "Overview of your local dev & AI environments",
        "dashboard.refresh": "Refresh",
        "dashboard.runtimeSuffix": "Runtime",
        "dashboard.current": "Current",
        "dashboard.notSet": "Not Set",
        "dashboard.system": "System",
        "dashboard.installed": "installed",
        "dashboard.configured": "configured",
        "dashboard.storage": "Storage",
        "dashboard.skills": "Skills",
        "dashboard.mcpServers": "MCP Servers",
        "dashboard.activeRuntimes": "Active Runtimes",
        "dashboard.managed": "Managed",
        "dashboard.section.runtimes": "Runtimes",
        "dashboard.section.overview": "Overview",
        "dashboard.section.packages": "Package Managers",
        "dashboard.package.cacheSize": "Cache size",
        "dashboard.package.needsCleanup": "Consider cleaning up",
        "dashboard.attention": "Needs attention",
        "dashboard.storage.subtitle": "Used by managed versions",
        "dashboard.card.openHint": "Open details",

        "runtime.installed": "Installed",
        "runtime.available": "Available",
        "runtime.active": "Active",
        "runtime.none": "None",
        "runtime.systemDefault": "System Default",
        "runtime.refresh": "Refresh",
        "runtime.loading": "Loading versions...",
        "runtime.noAvailable": "No available versions.",
        "runtime.noInstalled": "No installed versions. Switch to Available to install one.",
        "runtime.install": "Install",
        "runtime.installedLabel": "Installed",
        "runtime.setActive": "Set Active",
        "runtime.uninstall": "Uninstall",
        "runtime.uninstallTitle": "Uninstall %@?",
        "runtime.cancel": "Cancel",
        "runtime.revealInFinder": "Reveal in Finder",
        "runtime.uninstallSystemMessage": "EnvMatrix will remove the folder:\n%@\n\nIf it was installed via brew / sdkman / nvm / pkg, using its own uninstaller is safer. Paths owned by the OS may require sudo and will be rejected.",
        "runtime.uninstallMessage": "This will remove %@ %@ from your system.",
        "runtime.uninstallSystemTooltip": "Uninstall this system runtime (will confirm before deleting)",
        "runtime.uninstallTooltip": "Uninstall this version",
        "runtime.systemBadge": "System",

        "skills.title": "Skills",
        "skills.refresh": "Refresh",
        "skills.empty.title": "No Skills Found",
        "skills.empty.subtitle": "Configured skills directories are empty.",
        "skills.revealInFinder": "Reveal in Finder",
        "skills.delete": "Delete",

        "cli.title": "AI CLI",
        "cli.save": "Save",
        "cli.selectPrompt": "Select a CLI configuration",
        "cli.selectHint": "Choose a configuration on the left to edit its values.",
        "cli.model": "Model",
        "cli.apiBaseURL": "API Base URL",
        "cli.apiKey": "API Key",

        "mcp.title": "MCP Servers",
        "mcp.add": "Add",
        "mcp.refresh": "Refresh",
        "mcp.empty.title": "No MCP Servers",
        "mcp.empty.subtitle": "Click Add to configure a new server.",
        "mcp.edit": "Edit",
        "mcp.delete": "Delete",
        "mcp.argCount.one": "%d arg",
        "mcp.argCount.many": "%d args",
        "mcp.editor.editTitle": "Edit MCP Server",
        "mcp.editor.addTitle": "Add MCP Server",
        "mcp.editor.basics": "Basics",
        "mcp.editor.name": "Name",
        "mcp.editor.command": "Command",
        "mcp.editor.arguments": "Arguments",
        "mcp.editor.argsPlaceholder": "Comma-separated",
        "mcp.editor.argsHelp": "Values separated by commas, e.g. --port,8080",
        "mcp.editor.envVars": "Environment Variables",
        "mcp.editor.envKey": "KEY",
        "mcp.editor.envValue": "value",
        "mcp.editor.addVariable": "Add Variable",
        "mcp.editor.cancel": "Cancel",
        "mcp.editor.save": "Save",

        "settings.general": "General",
        "settings.logs": "Logs",
        "settings.about": "About",
        "settings.appearance": "Appearance",
        "settings.colorScheme": "Color Scheme",
        "settings.system": "System",
        "settings.light": "Light",
        "settings.dark": "Dark",
        "settings.language": "Language",
        "settings.languageLabel": "Interface Language",
        "settings.mirrors": "Mirror Sources",
        "settings.nodeMirror": "Node.js Mirror",
        "settings.pythonMirror": "Python Mirror",
        "settings.goMirror": "Go Mirror",
        "settings.javaMirror": "Java Mirror",
        "settings.resetDefaults": "Reset to Defaults",
        "settings.entries": "%d entries",
        "settings.clear": "Clear",
        "settings.noLogs": "No log entries.",
        "settings.version": "Version %@",
        "settings.aboutDescription": "A unified macOS control panel for managing developer runtimes and AI development environments.",
        "settings.viewGitHub": "View on GitHub",

        "brew.title": "Homebrew",
        "brew.notInstalled.title": "Homebrew Not Found",
        "brew.notInstalled.subtitle": "EnvMatrix couldn't find a `brew` executable at /opt/homebrew/bin/brew or /usr/local/bin/brew. Install Homebrew to manage packages here.",
        "brew.formulae": "Formulae",
        "brew.casks": "Casks",
        "brew.refresh": "Refresh",
        "brew.loading": "Loading Homebrew inventory…",
        "brew.emptyList": "No packages match the current filters.",
        "brew.searchPlaceholder": "Search name or description",
        "brew.outdatedCount": "%d outdated",
        "brew.upgradeAll": "Upgrade All",
        "brew.cleanup": "Cleanup",
        "brew.update": "brew update",
        "brew.filter.outdatedOnly": "Outdated only",
        "brew.filter.requestedOnly": "Requested only",
        "brew.action.upgrade": "Upgrade",
        "brew.action.uninstall": "Uninstall",
        "brew.action.pin": "Pin",
        "brew.action.unpin": "Unpin",
        "brew.action.openHomepage": "Open Homepage",
        "brew.detail.selectHint": "Select a package to see details.",
        "brew.detail.kind": "Kind",
        "brew.detail.installedVersion": "Installed",
        "brew.detail.latestVersion": "Latest",
        "brew.detail.homepage": "Homepage",
        "brew.detail.autoUpdates": "Auto Updates",
        "brew.detail.installedAt": "Installed At",
        "brew.detail.deprecationReason": "Deprecation",
        "brew.detail.dependencies": "Dependencies",
        "brew.yes": "Yes",
        "brew.no": "No",

        "mavenRepo.title": "Maven Repository",
        "mavenRepo.subtitle": "Manage settings.xml mirrors and local ~/.m2/repository artifacts",
        "mavenRepo.refresh": "Refresh",
        "mavenRepo.addPreset": "Add Preset",
        "mavenRepo.settingsFile": "settings.xml:",
        "mavenRepo.localRepository": "localRepository:",
        "mavenRepo.active": "Active",
        "mavenRepo.mirrorOfFormat": "mirrorOf: %@",
        "mavenRepo.empty.title": "No Mirrors Configured",
        "mavenRepo.empty.subtitle": "Use the + button to add a preset mirror (Aliyun, Tencent, HuaweiCloud, Netease).",
        "mavenRepo.tab.mirrors": "Mirrors",
        "mavenRepo.tab.localArtifacts": "Local Artifacts",
        "mavenRepo.artifact.searchPlaceholder": "Search groupId, artifactId or version",
        "mavenRepo.artifact.countFormat": "%d artifacts",
        "mavenRepo.artifact.totalSizeFormat": "Total: %@",
        "mavenRepo.artifact.versionCountFormat": "%d versions",
        "mavenRepo.artifact.sortByName": "Sort by Name",
        "mavenRepo.artifact.sortBySize": "Sort by Size",
        "mavenRepo.artifact.sortByModified": "Sort by Modified",
        "mavenRepo.artifact.ascending": "Ascending",
        "mavenRepo.artifact.loading": "Scanning local repository…",
        "mavenRepo.artifact.notFound.title": "Local Repository Not Found",
        "mavenRepo.artifact.notFound.subtitle": "No directory at %@\n\nRun a Maven build first to populate ~/.m2/repository.",
        "mavenRepo.artifact.empty.title": "No Artifacts",
        "mavenRepo.artifact.empty.subtitle": "No downloaded artifacts match your search.",
        "mavenRepo.artifact.deleteAll": "Delete all versions",
        "mavenRepo.artifact.confirmDelete": "Delete %@?",
        "mavenRepo.artifact.confirmDeleteVersion": "Delete %@ (%@)?",
        "mavenRepo.artifact.confirmDeleteMessage": "This will remove %@ from disk. This action cannot be undone.",

        "nav.goRepo": "Go Repository",
        "nav.nodeRepo": "Node Repository",
        "goRepo.title": "Go Repository",
        "goRepo.subtitle": "Manage GOPROXY mirror and clean local GOMODCACHE",
        "goRepo.tab.proxy": "GOPROXY",
        "goRepo.tab.localCache": "Local Modules",
        "goRepo.proxy.current": "Current GOPROXY:",
        "goRepo.proxy.applyPreset": "Apply Preset",
        "goRepo.proxy.customPlaceholder": "Custom GOPROXY (comma-separated)",
        "goRepo.proxy.save": "Save",
        "goRepo.proxy.saved": "GOPROXY updated",
        "goRepo.cache.searchPlaceholder": "Search module or version",
        "goRepo.cache.countFormat": "%d modules",
        "goRepo.cache.totalSizeFormat": "Total: %@",
        "goRepo.cache.versionCountFormat": "%d versions",
        "goRepo.cache.sortByName": "Sort by Name",
        "goRepo.cache.sortBySize": "Sort by Size",
        "goRepo.cache.sortByModified": "Sort by Modified",
        "goRepo.cache.ascending": "Ascending",
        "goRepo.cache.loading": "Scanning GOMODCACHE…",
        "goRepo.cache.notFound.title": "GOMODCACHE Not Found",
        "goRepo.cache.notFound.subtitle": "No directory at %@\n\nRun a Go build first to populate the module cache.",
        "goRepo.cache.empty.title": "No Modules",
        "goRepo.cache.empty.subtitle": "No downloaded modules match your search.",
        "goRepo.cache.deleteAll": "Delete all versions",
        "goRepo.cache.confirmDelete": "Delete %@?",
        "goRepo.cache.confirmDeleteVersion": "Delete %@ (%@)?",
        "goRepo.cache.confirmDeleteMessage": "This will remove %@ from disk. This action cannot be undone.",
        "goRepo.goMissing.title": "Go Not Found",
        "goRepo.goMissing.subtitle": "The `go` command is not on PATH. Install Go from EnvMatrix Dev Environments first.",
        "nodeRepo.title": "Node Repository",
        "nodeRepo.subtitle": "Manage npm registry, global packages and cache",
        "nodeRepo.tab.registry": "Registry",
        "nodeRepo.tab.global": "Global Packages",
        "nodeRepo.tab.cache": "Cache",
        "nodeRepo.registry.current": "Current registry:",
        "nodeRepo.registry.applyPreset": "Apply Preset",
        "nodeRepo.registry.customPlaceholder": "Custom registry URL",
        "nodeRepo.registry.save": "Save",
        "nodeRepo.registry.saved": "Registry updated",
        "nodeRepo.registry.confirmTitle": "Update npm registry?",
        "nodeRepo.registry.confirmMessage": "The value in ~/.npmrc will change to %@. A backup will be written to ~/.npmrc.envmatrix.bak.",
        "nodeRepo.global.searchPlaceholder": "Search package name",
        "nodeRepo.global.countFormat": "%d packages",
        "nodeRepo.global.loading": "Loading global packages…",
        "nodeRepo.global.empty.title": "No Global Packages",
        "nodeRepo.global.empty.subtitle": "There are no user-installed global npm packages.",
        "nodeRepo.global.uninstall": "Uninstall",
        "nodeRepo.global.confirmUninstall": "Uninstall %@?",
        "nodeRepo.global.confirmUninstallMessage": "This will run `npm uninstall -g %@`.",
        "nodeRepo.cache.location": "Cache location:",
        "nodeRepo.cache.sizeFormat": "Size: %@",
        "nodeRepo.cache.clean": "Clean Cache",
        "nodeRepo.cache.confirmClean": "Clean npm cache?",
        "nodeRepo.cache.confirmCleanMessage": "This will run `npm cache clean --force`. Downloaded tarballs will need to be re-fetched.",
        "nodeRepo.cache.cleaned": "Cache cleaned",
        "nodeRepo.npmMissing.title": "npm Not Found",
        "nodeRepo.npmMissing.subtitle": "The `npm` command is not on PATH. Install Node.js from EnvMatrix Dev Environments first.",
        "nodeRepo.tab.globalPkg": "Global Packages",
        "nodeRepo.registry.presets": "Preset mirrors",
        "nodeRepo.registry.custom": "Custom URL",
        "nodeRepo.registry.apply": "Apply",
        "nodeRepo.registry.confirmApply": "Switch npm registry?",
        "nodeRepo.msg.saved": "Saved",
        "nodeRepo.msg.invalidURL": "URL must start with http:// or https://",
        "nodeRepo.pkg.uninstall": "Uninstall",
        "nodeRepo.pkg.confirmDelete": "Uninstall this global package?",
        "nodeRepo.pkg.empty": "No global packages installed",
        "nodeRepo.pkg.search": "Search packages",
        "nodeRepo.pkg.total": "%d total",
        "nodeRepo.cache.path": "Cache directory",
        "nodeRepo.cache.size": "Cache size",
        "common.refresh": "Refresh",
        "common.cancel": "Cancel",
        "common.confirm": "Confirm",

        "settings.backups": "Backups",
        "settings.backups.title": "Configuration Backups",
        "settings.backups.subtitle": "Backups automatically created before EnvMatrix modifies your configuration files. You can restore or delete them here.",
        "settings.backups.empty": "No backups found. Backups will appear here after you apply a mirror or edit configuration through EnvMatrix.",
        "settings.backups.column.file": "Backup File",
        "settings.backups.column.target": "Target",
        "settings.backups.column.time": "Modified",
        "settings.backups.column.size": "Size",
        "settings.backups.restore": "Restore",
        "settings.backups.delete": "Delete",
        "settings.backups.reveal": "Reveal in Finder",
        "settings.backups.confirmRestore": "Restore backup? This will overwrite %@.",
        "settings.backups.confirmDelete": "Delete this backup? This cannot be undone.",
        "settings.backups.restoreSuccess": "Restored %@ from backup.",
        "settings.backups.deleteSuccess": "Backup deleted.",
        "settings.backups.kind.npmrc": "npm registry (.npmrc)",
        "settings.backups.kind.mavenSettings": "Maven settings.xml",

        "globalSearch.placeholder": "Search across package managers…",
        "globalSearch.hint.title": "Search everything",
        "globalSearch.hint.subtitle": "Type to search Homebrew, Maven, Go modules and global npm packages at once.",
        "globalSearch.noResults": "No matching results",
        "globalSearch.source.brew": "Homebrew",
        "globalSearch.source.maven": "Maven",
        "globalSearch.source.go": "Go",
        "globalSearch.source.node": "npm",

        "settings.diagnostics": "Diagnostics",
        "settings.diagnostics.title": "Diagnostic report",
        "settings.diagnostics.subtitle": "A Markdown snapshot of the current machine's package managers, ready to attach to issues.",
        "settings.diagnostics.generate": "Generate report",
        "settings.diagnostics.copy": "Copy",
        "settings.diagnostics.save": "Save as Markdown…",
        "settings.diagnostics.copied": "Copied to clipboard",
        "settings.diagnostics.emptyHint": "Click ‘Generate report’ to scan Homebrew / Maven / Go / npm."
    ]
}
