import Foundation
import AppKit

/// Assembles a human-readable Markdown snapshot of the current machine's
/// package-manager landscape. Intended to be attached to bug reports or
/// pasted into a chat when asking for help.
public struct DiagnosticReportService {
    private let brewService: HomebrewService
    private let mavenService: MavenLocalRepositoryService
    private let goService: GoLocalCacheService
    private let npmService: NpmService
    private let npmrcService: NpmrcService

    public init(
        brewService: HomebrewService = DefaultHomebrewService(),
        mavenService: MavenLocalRepositoryService = DefaultMavenLocalRepositoryService(),
        goService: GoLocalCacheService = DefaultGoLocalCacheService(),
        npmService: NpmService = DefaultNpmService(),
        npmrcService: NpmrcService = DefaultNpmrcService()
    ) {
        self.brewService = brewService
        self.mavenService = mavenService
        self.goService = goService
        self.npmService = npmService
        self.npmrcService = npmrcService
    }

    /// Build the report. Safe to call from any actor; internally offloads
    /// I/O-heavy calls onto a detached task.
    public func makeReport() async -> String {
        var lines: [String] = []
        let now = ISO8601DateFormatter().string(from: Date())

        lines.append("# EnvMatrix Diagnostic Report")
        lines.append("")
        lines.append("- Generated: \(now)")
        lines.append("- OS: macOS \(ProcessInfo.processInfo.operatingSystemVersionString)")
        if let bundle = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String {
            lines.append("- App version: \(bundle)")
        }
        lines.append("- Locale: \(Locale.current.identifier)")
        lines.append("- CPU cores: \(ProcessInfo.processInfo.processorCount)")
        lines.append("")

        // Homebrew
        lines.append("## Homebrew")
        if brewService.isAvailable {
            lines.append("- Binary: `\(brewService.brewPath)`")
            if let inv = try? await brewService.inventory(forceRefresh: false) {
                lines.append("- Formulae installed: \(inv.formulae.count)")
                lines.append("- Casks installed: \(inv.casks.count)")
                lines.append("- Outdated: \(inv.outdatedCount)")
                lines.append("- brew version: \(inv.brewVersion)")
            } else {
                lines.append("- Inventory: unavailable")
            }
        } else {
            lines.append("- Not detected on PATH")
        }
        lines.append("")

        // Maven
        let mavenBytes = await Task.detached(priority: .utility) { () -> Int64 in
            (try? self.mavenService.totalSize()) ?? 0
        }.value
        let mavenCount = await Task.detached(priority: .utility) { () -> Int in
            (try? self.mavenService.scan().count) ?? 0
        }.value
        lines.append("## Maven")
        lines.append("- Local repository size: \(formatBytes(mavenBytes))")
        lines.append("- Artifacts: \(mavenCount)")
        lines.append("")

        // Go
        let goBytes = await Task.detached(priority: .utility) { () -> Int64 in
            (try? self.goService.totalSize()) ?? 0
        }.value
        let goCount = await Task.detached(priority: .utility) { () -> Int in
            (try? self.goService.scan().count) ?? 0
        }.value
        lines.append("## Go modules")
        lines.append("- GOMODCACHE size: \(formatBytes(goBytes))")
        lines.append("- Modules cached: \(goCount)")
        lines.append("")

        // npm
        lines.append("## npm")
        let npmAvailable = await npmService.isNpmAvailable()
        if npmAvailable {
            let globalCount = (try? await npmService.listGlobalPackages().count) ?? 0
            let cache = try? await npmService.cacheStats()
            lines.append("- Global packages: \(globalCount)")
            if let cache = cache {
                lines.append("- Cache path: `\(cache.path)`")
                lines.append("- Cache size: \(formatBytes(cache.sizeBytes))")
            }
            if let registry = try? npmrcService.readRegistry() {
                let display = registry.isEmpty ? "(default)" : registry
                lines.append("- Registry: `\(display)`")
            }
        } else {
            lines.append("- npm not detected on PATH")
        }
        lines.append("")

        lines.append("---")
        lines.append("_Generated by EnvMatrix. Feel free to attach this to an issue._")
        return lines.joined(separator: "\n")
    }

    private func formatBytes(_ bytes: Int64) -> String {
        let bcf = ByteCountFormatter()
        bcf.allowedUnits = [.useMB, .useGB, .useKB, .useBytes]
        bcf.countStyle = .file
        return bcf.string(fromByteCount: bytes)
    }
}
